/* ===== LingoNest — content.js : registries + shared course structure =====
   Loaded first. Holds everything that is the SAME for all target languages:
   language list, concept list (id, category, level, Hebrew + English meaning), categories, dialogues.
   Per-language text lives in lang-xx.js and is loaded on demand. */
'use strict';
window.__MODS = window.__MODS || {};
const LANG = {};                                  /* UI dictionaries (filled by ui-xx.js) */
const ALPHA = {}, VOWELS = {}, TONES = {}, TWISTER = {}, WD = {}, GENDER_F = {}, CUR_SYM = {}, LANG_NOTE = {};
const LOADED = {};                                /* lang code → version of the loaded pack */

/* Target languages. To add one: add a line here + create lang-xx.js (copy an existing pack) + add it to sw.js. */
const LANGS = {
  en: { flag: "🇬🇧", tts: "en-US", dir: "ltr", native: "English", name: {"he":"אנגלית","en":"English","ru":"Английский","es":"Inglés","ar":"الإنجليزية"} },
  es: { flag: "🇪🇸", tts: "es-ES", dir: "ltr", native: "Español", name: {"he":"ספרדית","en":"Spanish","ru":"Испанский","es":"Español","ar":"الإسبانية"} },
  ru: { flag: "🇷🇺", tts: "ru-RU", dir: "ltr", native: "Русский", name: {"he":"רוסית","en":"Russian","ru":"Русский","es":"Ruso","ar":"الروسية"} },
  ar: { flag: "🇸🇦", tts: "ar-SA", dir: "rtl", native: "العربية", name: {"he":"ערבית","en":"Arabic","ru":"Арабский","es":"Árabe","ar":"العربية"} },
  th: { flag: "🇹🇭", tts: "th-TH", dir: "ltr", native: "ภาษาไทย", name: {"he":"תאילנדית","en":"Thai","ru":"Тайский","es":"Tailandés","ar":"التايلاندية"} }
};
/* Short letters-screen notes (keys in ui-xx.js). New languages can instead pass note:{he,en,...} in their pack. */
const ALPHA_NOTE = {"en":"noteEn","es":"noteEs","ru":"noteRu","ar":"noteAr","th":"noteTh"};

/* Levels: 1 letters · 2 survival · 3 travel vocab · 4 travel phrases · 5 everyday · 6 conversation · 7 world of words · 8 full sentences · 9 my words */
const MAXL = 9;

/* Categories (names come from ui-xx.js as cat_<id>) */
const CAT_ICON = { greet: '👋', num: '🔢', basic: '⭐', food: '🍜', trans: '🚕', shop: '🛍️', emerg: '🚑', time: '🕒', phr: '🗣️', mine: '✏️',
  hotel: '🏨', days: '📅', colors: '🎨', people: '👨‍👩‍👧', body: '🩺', adj: '↔️', verbs: '🏃', conv: '💬',
  animals: '🐘', fruits: '🍍', veggies: '🥕', dishes: '🍲', places: '🏛️', things: '🎒',
  s_food: '🍽️', s_shop: '🛒', s_move: '🚌', s_hotel: '🛎️', s_social: '🤝', s_help: '🆘', weather: '🌦️', jobs: '👷', feel: '😊', dirs: '🧭' };
const WORD_CATS = ['greet', 'num', 'basic', 'food', 'fruits', 'veggies', 'dishes', 'trans', 'dirs', 'places', 'shop', 'things', 'hotel', 'time', 'weather', 'days', 'colors', 'people', 'jobs', 'body', 'feel', 'animals', 'adj', 'verbs', 'emerg', 'mine'];
const PHRASE_CATS = ['phr', 'conv', 's_food', 's_shop', 's_move', 's_hotel', 's_social', 's_help'];
const isPhraseCat = c => c === 'phr' || c === 'conv' || c.startsWith('s_') || c.startsWith('dlg_');

/* Concepts: [id, category, level, Hebrew meaning, English meaning]. The id is the permanent key for progress — never rename one. */
const CONCEPTS = [
  /* greet */
  ["hello","greet",2,"שלום","Hello"],
  ["bye","greet",2,"להתראות","Goodbye"],
  ["morning","greet",2,"בוקר טוב","Good morning"],
  ["thanks","greet",2,"תודה","Thank you"],
  ["please","greet",2,"בבקשה","Please"],
  ["sorry","greet",2,"סליחה","Sorry"],
  ["yes","greet",2,"כן","Yes"],
  ["no","greet",2,"לא","No"],
  ["howareyou","greet",2,"מה שלומך?","How are you?"],
  ["good","greet",2,"טוב","Good"],
  ["ok","greet",2,"בסדר","OK"],
  /* num */
  ["n1","num",2,"1 · אחת","1 · One"],
  ["n2","num",2,"2 · שתיים","2 · Two"],
  ["n3","num",2,"3 · שלוש","3 · Three"],
  ["n4","num",2,"4 · ארבע","4 · Four"],
  ["n5","num",2,"5 · חמש","5 · Five"],
  ["n6","num",2,"6 · שש","6 · Six"],
  ["n7","num",2,"7 · שבע","7 · Seven"],
  ["n8","num",2,"8 · שמונה","8 · Eight"],
  ["n9","num",2,"9 · תשע","9 · Nine"],
  ["n10","num",2,"10 · עשר","10 · Ten"],
  ["n0","num",5,"0 · אפס","0 · Zero"],
  ["n20","num",5,"20 · עשרים","20 · Twenty"],
  ["n50","num",5,"50 · חמישים","50 · Fifty"],
  ["n100","num",5,"100 · מאה","100 · One hundred"],
  ["n1000","num",5,"1000 · אלף","1000 · One thousand"],
  ["n11","num",5,"11 · אחת עשרה","11 · Eleven"],
  ["n12","num",5,"12 · שתים עשרה","12 · Twelve"],
  ["n13","num",5,"13 · שלוש עשרה","13 · Thirteen"],
  ["n14","num",5,"14 · ארבע עשרה","14 · Fourteen"],
  ["n15","num",5,"15 · חמש עשרה","15 · Fifteen"],
  ["n16","num",5,"16 · שש עשרה","16 · Sixteen"],
  ["n17","num",5,"17 · שבע עשרה","17 · Seventeen"],
  ["n18","num",5,"18 · שמונה עשרה","18 · Eighteen"],
  ["n19","num",5,"19 · תשע עשרה","19 · Nineteen"],
  ["n30","num",5,"30 · שלושים","30 · Thirty"],
  ["n40","num",5,"40 · ארבעים","40 · Forty"],
  ["n60","num",5,"60 · שישים","60 · Sixty"],
  ["n70","num",5,"70 · שבעים","70 · Seventy"],
  ["n80","num",5,"80 · שמונים","80 · Eighty"],
  ["n90","num",5,"90 · תשעים","90 · Ninety"],
  ["n200","num",5,"200 · מאתיים","200 · Two hundred"],
  ["n500","num",5,"500 · חמש מאות","500 · Five hundred"],
  ["n10000","num",5,"10,000 · עשרת אלפים","10,000 · Ten thousand"],
  /* basic */
  ["water","basic",2,"מים","Water"],
  ["toilet","basic",2,"שירותים","Toilet"],
  ["where","basic",2,"איפה?","Where?"],
  ["howmuch","basic",2,"כמה?","How much?"],
  ["this","basic",2,"זה","This"],
  ["friend","basic",2,"חבר","Friend"],
  /* food */
  ["food","food",3,"אוכל","Food"],
  ["bread","food",3,"לחם","Bread"],
  ["coffee","food",3,"קפה","Coffee"],
  ["tea","food",3,"תה","Tea"],
  ["chicken","food",3,"עוף","Chicken"],
  ["fish","food",3,"דג","Fish"],
  ["rice","food",3,"אורז","Rice"],
  ["beer","food",3,"בירה","Beer"],
  ["bill","food",3,"החשבון","The bill"],
  ["tasty","food",3,"טעים","Delicious"],
  ["egg","food",3,"ביצה","Egg"],
  ["fruit","food",3,"פירות","Fruit"],
  ["veg","food",3,"ירקות","Vegetables"],
  ["meat","food",3,"בשר","Meat"],
  ["milk","food",3,"חלב","Milk"],
  ["spicy","food",3,"חריף","Spicy"],
  ["restaurant","food",3,"מסעדה","Restaurant"],
  ["ice","food",3,"קרח","Ice"],
  /* trans */
  ["taxi","trans",3,"מונית","Taxi"],
  ["bus","trans",3,"אוטובוס","Bus"],
  ["train","trans",3,"רכבת","Train"],
  ["airport","trans",3,"שדה תעופה","Airport"],
  ["hotel","trans",3,"מלון","Hotel"],
  ["left","trans",3,"שמאלה","Left"],
  ["right","trans",3,"ימינה","Right"],
  ["straight","trans",3,"ישר","Straight ahead"],
  ["stop","trans",3,"עצור","Stop"],
  ["ticket","trans",3,"כרטיס","Ticket"],
  /* shop */
  ["money","shop",3,"כסף","Money"],
  ["expensive","shop",3,"יקר","Expensive"],
  ["cheap","shop",3,"זול","Cheap"],
  ["market","shop",3,"שוק","Market"],
  ["pharmacy","shop",3,"בית מרקחת","Pharmacy"],
  ["open","shop",3,"פתוח","Open"],
  ["closed","shop",3,"סגור","Closed"],
  /* emerg */
  ["help","emerg",3,"הצילו!","Help!"],
  ["police","emerg",3,"משטרה","Police"],
  ["doctor","emerg",3,"רופא","Doctor"],
  ["hospital","emerg",3,"בית חולים","Hospital"],
  /* time */
  ["today","time",3,"היום","Today"],
  ["tomorrow","time",3,"מחר","Tomorrow"],
  ["yesterday","time",3,"אתמול","Yesterday"],
  ["now","time",3,"עכשיו","Now"],
  ["t_morning","time",5,"בוקר","Morning"],
  ["t_evening","time",5,"ערב","Evening"],
  ["t_night","time",5,"לילה","Night"],
  ["t_week","time",5,"שבוע","Week"],
  ["t_month","time",5,"חודש","Month"],
  ["t_year","time",5,"שנה","Year"],
  ["t_hour","time",5,"שעה","Hour"],
  ["t_minute","time",5,"דקה","Minute"],
  /* phr */
  ["p_toilet","phr",4,"איפה השירותים?","Where is the toilet?"],
  ["p_cost","phr",4,"כמה זה עולה?","How much does it cost?"],
  ["p_nounder","phr",4,"אני לא מבין","I don't understand"],
  ["p_english","phr",4,"אתה מדבר אנגלית?","Do you speak English?"],
  ["p_slow","phr",4,"דבר לאט בבקשה","Please speak slowly"],
  ["p_bill","phr",4,"את החשבון בבקשה","The bill, please"],
  ["p_want","phr",4,"אני רוצה את זה","I want this one"],
  ["p_expensive","phr",4,"זה יקר מדי","It's too expensive"],
  ["p_discount","phr",4,"אפשר הנחה?","Can I get a discount?"],
  ["p_address","phr",4,"קח אותי לכתובת הזאת","Take me to this address"],
  ["p_hotel","phr",4,"איפה המלון?","Where is the hotel?"],
  ["p_doctor","phr",4,"אני צריך רופא","I need a doctor"],
  ["p_police","phr",4,"תתקשר למשטרה!","Call the police!"],
  ["p_israel","phr",4,"אני מישראל","I'm from Israel"],
  ["p_name","phr",4,"קוראים לי...","My name is..."],
  ["p_nice","phr",4,"נעים מאוד","Nice to meet you"],
  ["p_water","phr",4,"מים בבקשה","Water, please"],
  ["p_help","phr",4,"אתה יכול לעזור לי?","Can you help me?"],
  ["p_what","phr",4,"מה זה?","What is this?"],
  ["p_nospicy","phr",4,"בלי חריף בבקשה","Not spicy, please"],
  /* hotel */
  ["room","hotel",3,"חדר","Room"],
  ["key","hotel",3,"מפתח","Key"],
  ["bed","hotel",3,"מיטה","Bed"],
  ["shower","hotel",3,"מקלחת","Shower"],
  ["towel","hotel",3,"מגבת","Towel"],
  ["passport","hotel",3,"דרכון","Passport"],
  /* days */
  ["mon","days",5,"יום שני","Monday"],
  ["tue","days",5,"יום שלישי","Tuesday"],
  ["wed","days",5,"יום רביעי","Wednesday"],
  ["thu","days",5,"יום חמישי","Thursday"],
  ["fri","days",5,"יום שישי","Friday"],
  ["sat","days",5,"שבת","Saturday"],
  ["sun","days",5,"יום ראשון","Sunday"],
  /* colors */
  ["red","colors",5,"אדום","Red"],
  ["blue","colors",5,"כחול","Blue"],
  ["green","colors",5,"ירוק","Green"],
  ["yellow","colors",5,"צהוב","Yellow"],
  ["black","colors",5,"שחור","Black"],
  ["white","colors",5,"לבן","White"],
  /* people */
  ["man","people",5,"גבר","Man"],
  ["woman","people",5,"אישה","Woman"],
  ["child","people",5,"ילד","Child"],
  ["family","people",5,"משפחה","Family"],
  ["i","people",5,"אני","I"],
  ["you","people",5,"אתה / את","You"],
  /* body */
  ["head","body",5,"ראש","Head"],
  ["stomach","body",5,"בטן","Stomach"],
  ["hand","body",5,"יד","Hand"],
  ["pain","body",5,"כאב","Pain"],
  ["medicine","body",5,"תרופה","Medicine"],
  ["sick","body",5,"חולה","Sick"],
  /* adj */
  ["big","adj",5,"גדול","Big"],
  ["small","adj",5,"קטן","Small"],
  ["hot","adj",5,"חם","Hot"],
  ["cold","adj",5,"קר","Cold"],
  ["bad","adj",5,"רע","Bad"],
  ["beautiful","adj",5,"יפה","Beautiful"],
  ["new","adj",7,"חדש","New"],
  ["old","adj",7,"ישן","Old"],
  ["fast","adj",7,"מהיר","Fast"],
  ["slow","adj",7,"איטי","Slow"],
  ["near","adj",7,"קרוב","Near"],
  ["far_a","adj",7,"רחוק","Far"],
  ["clean","adj",7,"נקי","Clean"],
  ["dirty","adj",7,"מלוכלך","Dirty"],
  ["tired","adj",7,"עייף","Tired"],
  ["hungry","adj",7,"רעב","Hungry"],
  ["thirsty","adj",7,"צמא","Thirsty"],
  ["happy","adj",7,"שמח","Happy"],
  ["sad","adj",7,"עצוב","Sad"],
  ["easy","adj",7,"קל","Easy"],
  ["difficult","adj",7,"קשה","Difficult"],
  ["many","adj",7,"הרבה","Many / a lot"],
  /* verbs */
  ["eat","verbs",5,"לאכול","To eat"],
  ["drink","verbs",5,"לשתות","To drink"],
  ["go","verbs",5,"ללכת / לנסוע","To go"],
  ["buy","verbs",5,"לקנות","To buy"],
  ["speak","verbs",5,"לדבר","To speak"],
  ["sleep","verbs",5,"לישון","To sleep"],
  ["understand","verbs",5,"להבין","To understand"],
  ["come","verbs",7,"לבוא","To come"],
  ["want","verbs",7,"לרצות","To want"],
  ["need","verbs",7,"להצטרך","To need"],
  ["know","verbs",7,"לדעת","To know"],
  ["see","verbs",7,"לראות","To see"],
  ["hear","verbs",7,"לשמוע","To hear"],
  ["give","verbs",7,"לתת","To give"],
  ["take","verbs",7,"לקחת","To take"],
  ["pay","verbs",7,"לשלם","To pay"],
  ["wait","verbs",7,"לחכות","To wait"],
  ["walk","verbs",7,"ללכת ברגל","To walk"],
  ["read","verbs",7,"לקרוא","To read"],
  ["write","verbs",7,"לכתוב","To write"],
  ["love","verbs",7,"לאהוב","To love"],
  ["work","verbs",7,"לעבוד","To work"],
  ["swim","verbs",7,"לשחות","To swim"],
  /* conv */
  ["c_table","conv",6,"שולחן לשניים בבקשה","A table for two, please"],
  ["c_menu","conv",6,"אפשר תפריט?","Can I see the menu?"],
  ["c_noice","conv",6,"בלי קרח בבקשה","No ice, please"],
  ["c_nomeat","conv",6,"אני לא אוכל בשר","I don't eat meat"],
  ["c_allergy","conv",6,"יש לי אלרגיה לאגוזים","I'm allergic to nuts"],
  ["c_delicious","conv",6,"טעים מאוד!","Very delicious!"],
  ["c_reserv","conv",6,"יש לי הזמנה","I have a reservation"],
  ["c_wifi","conv",6,"מה הסיסמה של הוויי-פיי?","What's the Wi-Fi password?"],
  ["c_checkout","conv",6,"מתי צריך לפנות את החדר?","What time is checkout?"],
  ["c_howget","conv",6,"איך מגיעים לשם?","How do I get there?"],
  ["c_stophere","conv",6,"עצור כאן בבקשה","Stop here, please"],
  ["c_far","conv",6,"זה רחוק?","Is it far?"],
  ["c_card","conv",6,"אפשר לשלם בכרטיס?","Can I pay by card?"],
  ["c_looking","conv",6,"רק מסתכל, תודה","Just looking, thanks"],
  ["c_yourname","conv",6,"איך קוראים לך?","What's your name?"],
  ["c_wherefrom","conv",6,"מאיפה אתה?","Where are you from?"],
  ["c_seeyou","conv",6,"נתראה אחר כך","See you later"],
  ["c_cheers","conv",6,"לחיים!","Cheers!"],
  ["c_lost","conv",6,"הלכתי לאיבוד","I'm lost"],
  ["c_passport","conv",6,"איבדתי את הדרכון","I lost my passport"],
  ["c_hurts","conv",6,"כואב לי כאן","It hurts here"],
  ["c_time","conv",6,"מה השעה?","What time is it?"],
  ["c_again","conv",6,"תגיד שוב בבקשה","Please say that again"],
  ["c_write","conv",6,"אתה יכול לכתוב את זה?","Can you write it down?"],
  /* animals */
  ["dog","animals",7,"כלב","Dog"],
  ["cat","animals",7,"חתול","Cat"],
  ["bird","animals",7,"ציפור","Bird"],
  ["horse","animals",7,"סוס","Horse"],
  ["cow","animals",7,"פרה","Cow"],
  ["pig","animals",7,"חזיר","Pig"],
  ["elephant","animals",7,"פיל","Elephant"],
  ["monkey","animals",7,"קוף","Monkey"],
  ["snake","animals",7,"נחש","Snake"],
  ["mosquito","animals",7,"יתוש","Mosquito"],
  ["lion","animals",7,"אריה","Lion"],
  ["duck","animals",7,"ברווז","Duck"],
  /* fruits */
  ["apple","fruits",7,"תפוח","Apple"],
  ["banana","fruits",7,"בננה","Banana"],
  ["orange","fruits",7,"תפוז","Orange"],
  ["mango","fruits",7,"מנגו","Mango"],
  ["pineapple","fruits",7,"אננס","Pineapple"],
  ["watermelon","fruits",7,"אבטיח","Watermelon"],
  ["coconut","fruits",7,"קוקוס","Coconut"],
  ["grapes","fruits",7,"ענבים","Grapes"],
  ["lemon","fruits",7,"לימון","Lemon"],
  ["strawberry","fruits",7,"תות","Strawberry"],
  ["papaya","fruits",7,"פפאיה","Papaya"],
  /* veggies */
  ["tomato","veggies",7,"עגבנייה","Tomato"],
  ["potato","veggies",7,"תפוח אדמה","Potato"],
  ["onion","veggies",7,"בצל","Onion"],
  ["garlic","veggies",7,"שום","Garlic"],
  ["cucumber","veggies",7,"מלפפון","Cucumber"],
  ["carrot","veggies",7,"גזר","Carrot"],
  ["chili","veggies",7,"פלפל חריף","Chili pepper"],
  ["corn","veggies",7,"תירס","Corn"],
  ["mushroom","veggies",7,"פטרייה","Mushroom"],
  ["lettuce","veggies",7,"חסה","Lettuce"],
  ["eggplant","veggies",7,"חציל","Eggplant"],
  /* dishes */
  ["soup","dishes",7,"מרק","Soup"],
  ["salad","dishes",7,"סלט","Salad"],
  ["noodles","dishes",7,"אטריות","Noodles"],
  ["cheese","dishes",7,"גבינה","Cheese"],
  ["butter","dishes",7,"חמאה","Butter"],
  ["salt","dishes",7,"מלח","Salt"],
  ["sugar","dishes",7,"סוכר","Sugar"],
  ["cake","dishes",7,"עוגה","Cake"],
  ["icecream","dishes",7,"גלידה","Ice cream"],
  ["juice","dishes",7,"מיץ","Juice"],
  ["wine","dishes",7,"יין","Wine"],
  ["breakfast","dishes",7,"ארוחת בוקר","Breakfast"],
  ["lunch","dishes",7,"ארוחת צהריים","Lunch"],
  ["dinner","dishes",7,"ארוחת ערב","Dinner"],
  ["fork","dishes",7,"מזלג","Fork"],
  ["spoon","dishes",7,"כף","Spoon"],
  ["knife","dishes",7,"סכין","Knife"],
  ["glass","dishes",7,"כוס","Glass"],
  ["plate","dishes",7,"צלחת","Plate"],
  /* places */
  ["bank","places",7,"בנק","Bank"],
  ["atm","places",7,"כספומט","ATM"],
  ["beach","places",7,"חוף ים","Beach"],
  ["museum","places",7,"מוזיאון","Museum"],
  ["temple","places",7,"מקדש","Temple"],
  ["street","places",7,"רחוב","Street"],
  ["city","places",7,"עיר","City"],
  ["shop","places",7,"חנות","Shop"],
  ["supermarket","places",7,"סופרמרקט","Supermarket"],
  ["park","places",7,"פארק","Park"],
  ["station","places",7,"תחנה","Station"],
  ["embassy","places",7,"שגרירות","Embassy"],
  /* things */
  ["phone","things",7,"טלפון","Phone"],
  ["charger","things",7,"מטען","Charger"],
  ["bag","things",7,"תיק","Bag"],
  ["shoes","things",7,"נעליים","Shoes"],
  ["clothes","things",7,"בגדים","Clothes"],
  ["hat","things",7,"כובע","Hat"],
  ["glasses","things",7,"משקפיים","Glasses"],
  ["map","things",7,"מפה","Map"],
  ["sunscreen","things",7,"קרם הגנה","Sunscreen"],
  ["umbrella","things",7,"מטרייה","Umbrella"],
  /* s_food */
  ["sf_order","s_food",8,"אני רוצה להזמין","I'd like to order"],
  ["sf_recommend","s_food",8,"מה אתה ממליץ?","What do you recommend?"],
  ["sf_bottle","s_food",8,"בקבוק מים בבקשה","A bottle of water, please"],
  ["sf_isspicy","s_food",8,"זה חריף?","Is this spicy?"],
  ["sf_onemore","s_food",8,"עוד אחד בבקשה","One more, please"],
  ["sf_nosugar","s_food",8,"בלי סוכר בבקשה","Without sugar, please"],
  ["sf_takeaway","s_food",8,"אפשר לקחת את זה איתי?","Can I take this to go?"],
  /* s_shop */
  ["ss_smaller","s_shop",8,"יש מידה יותר קטנה?","Do you have a smaller size?"],
  ["ss_try","s_shop",8,"אפשר למדוד?","Can I try it on?"],
  ["ss_two","s_shop",8,"אני אקח שניים","I'll take two"],
  ["ss_change","s_shop",8,"יש לך עודף?","Do you have change?"],
  ["ss_last","s_shop",8,"מה המחיר הסופי?","What's the final price?"],
  ["ss_bag","s_shop",8,"אפשר שקית?","Can I have a bag?"],
  /* s_move */
  ["sm_busstop","s_move",8,"איפה תחנת האוטובוס?","Where is the bus stop?"],
  ["sm_trainleave","s_move",8,"מתי הרכבת יוצאת?","When does the train leave?"],
  ["sm_oneticket","s_move",8,"כרטיס אחד בבקשה","One ticket, please"],
  ["sm_howlong","s_move",8,"כמה זמן זה לוקח?","How long does it take?"],
  ["sm_meter","s_move",8,"תפעיל מונה בבקשה","Please use the meter"],
  ["sm_slowdrive","s_move",8,"סע לאט בבקשה","Please drive slowly"],
  ["sm_airport","s_move",8,"אני רוצה לנסוע לשדה התעופה","I want to go to the airport"],
  /* s_hotel */
  ["sh_leavebag","s_hotel",8,"אפשר להשאיר פה את התיק?","Can I leave my bag here?"],
  ["sh_ac","s_hotel",8,"המזגן לא עובד","The air conditioner doesn't work"],
  ["sh_breakfast","s_hotel",8,"ארוחת בוקר כלולה?","Is breakfast included?"],
  ["sh_towel","s_hotel",8,"אני צריך עוד מגבת","I need another towel"],
  ["sh_taxi","s_hotel",8,"אתה יכול להזמין לי מונית?","Can you call me a taxi?"],
  ["sh_late","s_hotel",8,"אפשר לפנות את החדר מאוחר יותר?","Can I check out later?"],
  /* s_social */
  ["so_learning","s_social",8,"אני לומד את השפה","I'm learning the language"],
  ["so_thankshelp","s_social",8,"תודה רבה על העזרה","Thank you very much for your help"],
  ["so_photo","s_social",8,"אתה יכול לצלם אותנו?","Can you take a photo of us?"],
  ["so_like","s_social",8,"אני אוהב את המקום הזה","I like this place"],
  ["so_vacation","s_social",8,"אני כאן בחופשה","I'm here on vacation"],
  ["so_howsay","s_social",8,"איך אומרים את זה?","How do you say this?"],
  ["so_noproblem","s_social",8,"אין בעיה","No problem"],
  ["so_beautiful","s_social",8,"זה מאוד יפה!","It's very beautiful!"],
  /* s_help */
  ["sp_unwell","s_help",8,"אני לא מרגיש טוב","I don't feel well"],
  ["sp_nearhosp","s_help",8,"איפה בית החולים הקרוב?","Where is the nearest hospital?"],
  ["sp_fever","s_help",8,"יש לי חום","I have a fever"],
  ["sp_helpme","s_help",8,"עזור לי בבקשה","Please help me"],
  ["sp_stolen","s_help",8,"גנבו לי את התיק","My bag was stolen"],
  ["sp_embassy","s_help",8,"אני צריך את שגרירות ישראל","I need the Israeli embassy"],
  /* dlg_taxi */
  ["dt1","dlg_taxi",8,"לאן?","Where to?"],
  ["dt2","dlg_taxi",8,"למלון הזה, בבקשה","To this hotel, please"],
  ["dt3","dlg_taxi",8,"בסדר, תעלה","OK, get in"],
  ["dt4","dlg_taxi",8,"כמה זה עולה?","How much is it?"],
  ["dt5","dlg_taxi",8,"מאתיים","Two hundred"],
  ["dt6","dlg_taxi",8,"תפעיל מונה בבקשה","Please use the meter"],
  ["dt7","dlg_taxi",8,"אין בעיה","No problem"],
  ["dt8","dlg_taxi",8,"עצור כאן, תודה","Stop here, thank you"],
  /* dlg_market */
  ["dm1","dlg_market",8,"כמה זה עולה?","How much is this?"],
  ["dm2","dlg_market",8,"שלוש מאות","Three hundred"],
  ["dm3","dlg_market",8,"יקר מדי! מאתיים?","Too expensive! Two hundred?"],
  ["dm4","dlg_market",8,"מאתיים חמישים, מחיר אחרון","Two hundred fifty, final price"],
  ["dm5","dlg_market",8,"בסדר, אני אקח","OK, I'll take it"],
  ["dm6","dlg_market",8,"תודה רבה!","Thank you very much!"],
  /* dlg_rest */
  ["dr1","dlg_rest",8,"כמה אנשים?","How many people?"],
  ["dr2","dlg_rest",8,"שניים בבקשה","Two, please"],
  ["dr3","dlg_rest",8,"מה תרצה להזמין?","What would you like to order?"],
  ["dr4","dlg_rest",8,"אורז מטוגן עם עוף, בלי חריף","Fried rice with chicken, not spicy"],
  ["dr5","dlg_rest",8,"ומה לשתות?","And to drink?"],
  ["dr6","dlg_rest",8,"מים בבקשה","Water, please"],
  ["dr7","dlg_rest",8,"את החשבון בבקשה","The bill, please"],
  /* dlg_hotel */
  ["dh1","dlg_hotel",8,"שלום, יש לי הזמנה","Hello, I have a reservation"],
  ["dh2","dlg_hotel",8,"על איזה שם?","Under what name?"],
  ["dh3","dlg_hotel",8,"על השם ...","The name is ..."],
  ["dh4","dlg_hotel",8,"את הדרכון בבקשה","Your passport, please"],
  ["dh5","dlg_hotel",8,"החדר שלך 305","Your room is 305"],
  ["dh6","dlg_hotel",8,"באיזו שעה ארוחת הבוקר?","What time is breakfast?"],
  ["dh7","dlg_hotel",8,"משבע עד עשר","From seven to ten"],
  /* dlg_dir */
  ["dd1","dlg_dir",8,"סליחה, איפה התחנה?","Excuse me, where is the station?"],
  ["dd2","dlg_dir",8,"ישר ואז שמאלה","Straight, then left"],
  ["dd3","dlg_dir",8,"זה רחוק מכאן?","Is it far from here?"],
  ["dd4","dlg_dir",8,"לא, חמש דקות ברגל","No, five minutes on foot"],
  ["dd5","dlg_dir",8,"תודה רבה!","Thanks a lot!"],
  /* weather */
  ["w_weather","weather",7,"מזג אוויר","Weather"],
  ["w_sun","weather",7,"שמש","Sun"],
  ["w_rain","weather",7,"גשם","Rain"],
  ["w_wind","weather",7,"רוח","Wind"],
  ["w_cloud","weather",7,"ענן","Cloud"],
  ["w_snow","weather",7,"שלג","Snow"],
  ["w_storm","weather",7,"סערה","Storm"],
  ["w_humid","weather",7,"לח","Humid"],
  /* jobs */
  ["j_teacher","jobs",7,"מורה","Teacher"],
  ["j_driver","jobs",7,"נהג","Driver"],
  ["j_waiter","jobs",7,"מלצר","Waiter"],
  ["j_cook","jobs",7,"טבח","Cook"],
  ["j_student","jobs",7,"סטודנט","Student"],
  ["j_engineer","jobs",7,"מהנדס","Engineer"],
  ["j_nurse","jobs",7,"אחות","Nurse"],
  ["j_seller","jobs",7,"מוכר","Seller"],
  ["j_guide","jobs",7,"מדריך טיולים","Tour guide"],
  ["j_pharmacist","jobs",7,"רוקח","Pharmacist"],
  /* feel */
  ["e_angry","feel",7,"כועס","Angry"],
  ["e_scared","feel",7,"מפחד","Scared"],
  ["e_bored","feel",7,"משועמם","Bored"],
  ["e_worried","feel",7,"דואג","Worried"],
  ["e_surprised","feel",7,"מופתע","Surprised"],
  ["e_calm","feel",7,"רגוע","Calm"],
  ["e_excited","feel",7,"נרגש","Excited"],
  ["e_love","feel",7,"מאוהב","In love"],
  /* dirs */
  ["dir_north","dirs",7,"צפון","North"],
  ["dir_south","dirs",7,"דרום","South"],
  ["dir_east","dirs",7,"מזרח","East"],
  ["dir_west","dirs",7,"מערב","West"],
  ["dir_corner","dirs",7,"פינה","Corner"],
  ["dir_light","dirs",7,"רמזור","Traffic light"],
  ["dir_behind","dirs",7,"מאחורי","Behind"],
  ["dir_front","dirs",7,"מלפנים","In front"],
  ["dir_next","dirs",7,"ליד","Next to"],
  ["dir_back","dirs",7,"אחורה","Back"],
  ["dir_up","dirs",7,"למעלה","Up"],
  ["dir_down","dirs",7,"למטה","Down"]
];

/* Dialogues: [id, icon, lines] — line = 'M:<concept>' (you) or 'T:<concept>' (the local person). Names: ui key dlg_<id> */
const DIALOGS = [["taxi","🚕",["T:dt1","M:dt2","T:dt3","M:dt4","T:dt5","M:dt6","T:dt7","M:dt8"]],["market","🛍️",["M:dm1","T:dm2","M:dm3","T:dm4","M:dm5","T:dm6"]],["rest","🍜",["T:dr1","M:dr2","T:dr3","M:dr4","T:dr5","M:dr6","M:dr7"]],["hotel","🏨",["M:dh1","T:dh2","M:dh3","T:dh4","T:dh5","M:dh6","T:dh7"]],["dir","🧭",["M:dd1","T:dd2","M:dd3","T:dd4","M:dd5"]]];

/* Registration API used by every lang-xx.js */
const LINGO = {
  registerLang(code, pack) {
    ALPHA[code] = pack.alpha || [];
    if (pack.vowels) VOWELS[code] = pack.vowels;
    if (pack.tones) TONES[code] = pack.tones;
    if (pack.twister) TWISTER[code] = pack.twister;
    if (pack.note) LANG_NOTE[code] = pack.note;
    CUR_SYM[code] = pack.curSym || '';
    GENDER_F[code] = (pack.gender || []).map(([src, flags, to]) => [new RegExp(src, flags), to]);
    const w = WD[code] = {};
    String(pack.words || '').split('\n').forEach(line => {
      const p = line.split('|');
      if (p.length >= 4) w[p[0].trim()] = [p[1].trim(), p[2].trim(), p[3].trim()];
    });
    LOADED[code] = pack.ver;
    window.__MODS['lang-' + code] = pack.ver;
  }
};
window.__MODS.content = '1.4.0';
