/* ===== LingoNest — help.js : the in-app user guide (loaded only when the guide opens) =====
   Each section: [id, icon, screen to open ('' = none), title {he,en}, body {he,en}]
   Body = array of lines; a line starting with "• " is a bullet. Other UI languages fall back to English. */
const HELP = [
['start', '🚀', '', {he: 'התחלה מהירה', en: 'Quick start'}, {
  he: ['LingoNest עוזרת לך ללמוד לדבר בשפה של היעד — מאותיות ומילים ראשונות ועד שיחה אמיתית.',
    '• בחר שפה בכרטיס בראש דף הבית.',
    '• לחץ על "המשך ללמוד" — האפליקציה בונה לך שיעור קצר לפי הרמה שלך, עם מילים חדשות וחזרות.',
    '• שמע כל מילה (🔊), גם לאט (🐢), והצג אותה בגדול (⛶) כדי להראות למקומי.',
    '• חזור כל יום לכמה דקות — הרצף 🔥 והיעד השבועי 🎯 יעזרו לך להתמיד.',
    'רוב האפליקציה עובדת בחינם ובלי אינטרנט. פיצ׳רים עם ✨ (שיחה עם בינה, דבר בשבילי ועוד) דורשים חיבור בינה — ראה "חיבור בינה".'],
  en: ['LingoNest helps you learn to speak your destination\'s language — from first letters and words to real conversation.',
    '• Pick a language on the card at the top of the home screen.',
    '• Tap "Continue learning" — the app builds a short lesson for your level, mixing new words and reviews.',
    '• Hear every word (🔊), slowly too (🐢), and show it big (⛶) to a local.',
    '• Come back daily for a few minutes — the streak 🔥 and weekly goal 🎯 keep you going.',
    'Most of the app is free and works offline. Features marked ✨ (AI chat, Speak for me…) need an AI connection — see "Connecting AI".']}],
['langs', '🌍', 'langs', {he: 'בחירת שפה', en: 'Choosing a language'}, {
  he: ['באפליקציה 28 שפות. לחץ על כרטיס השפה בדף הבית כדי לפתוח את מסך הבחירה.',
    '• חיפוש: אפשר לכתוב בעברית, באנגלית או בשפה עצמה (למשל "יפנ", "deutsch", "ไทย").',
    '• "השפות שלי" — השפות שכבר התחלת, עם אחוזי התקדמות.',
    '• שאר השפות מחולקות לאזורים: אירופה, המזרח התיכון והקווקז, אסיה ואפריקה.',
    '• בדף הבית, מתחת לכרטיס, מופיעות 3 השפות האחרונות — למעבר בלחיצה.',
    'ההתקדמות נשמרת לכל שפה בנפרד, כך שאפשר לעבור ביניהן בחופשיות.'],
  en: ['There are 28 languages. Tap the language card on the home screen to open the picker.',
    '• Search in Hebrew, English or the language itself ("japan", "deutsch", "ไทย").',
    '• "My languages" — the ones you\'ve started, with progress.',
    '• The rest are grouped by region: Europe, Middle East & Caucasus, Asia and Africa.',
    '• Under the card on the home screen, your 3 recent languages switch in one tap.',
    'Progress is kept per language, so you can switch freely.']}],
['home', '🏠', 'home', {he: 'דף הבית', en: 'The home screen'}, {
  he: ['• מילת היום — מילה חדשה בכל יום, עם הקראה.',
    '• הרמה הנוכחית ופס ההתקדמות שלה.',
    '• "המשך ללמוד" — השיעור היומי. מתחתיו: כמה חזרות מחכות וכמה מילים חדשות להיום.',
    '• 🎯 היעד השבועי ו-🔥 הרצף (ימים ברציפות).',
    '• אריחים לכל חלקי האפליקציה: אותיות, מילים, משפטים, תרגול, דיאלוגים, מחירים, שיחה עם בינה, ערכת טיול, טיפים, איך אומרים, דבר בשבילי וההתקדמות שלי.',
    '• למעלה: ⚙️ הגדרות, ℹ️ אודות, 🎨 ערכת צבעים, והעיגול — מעבר בין מצב יום ללילה.'],
  en: ['• Word of the day — a new word daily, with audio.',
    '• Your current level and its progress bar.',
    '• "Continue learning" — the daily lesson; below it, reviews due and new words for today.',
    '• 🎯 weekly goal and 🔥 streak.',
    '• Tiles for every part of the app.',
    '• Top: ⚙️ settings, ℹ️ about, 🎨 colour theme, and the dot toggles day/night mode.']}],
['levels', '🪜', 'progress', {he: 'רמות וחזרות מרווחות', en: 'Levels and spaced repetition'}, {
  he: ['הלימוד מחולק ל-9 רמות: 1 אותיות וצלילים · 2 הישרדות · 3 מילים לטיול · 4 משפטים לטיול · 5 מילים יומיומיות · 6 שיחה · 7 עולם המילים · 8 משפטים שלמים · 9 המילים שלי.',
    '• כשאתה שולט ב-70% מהרמה — נפתחת הבאה.',
    '• כל מילה עוברת "קופסאות" לפי כמה טוב אתה זוכר אותה: טעית — היא חוזרת מהר; ידעת — היא חוזרת אחרי יום, 3 ימים, שבוע, שבועיים וחודש.',
    '• כך אתה מתרגל בדיוק את מה שעומד להישכח, ולא מבזבז זמן על מה שכבר ידוע.'],
  en: ['Learning has 9 levels: 1 letters & sounds · 2 survival · 3 travel words · 4 travel phrases · 5 everyday words · 6 conversation · 7 world of words · 8 full sentences · 9 my words.',
    '• Master 70% of a level and the next one opens.',
    '• Each word moves through "boxes": miss it and it returns soon; know it and it returns after a day, 3 days, a week, two weeks, a month.',
    '• You practise exactly what\'s about to be forgotten.']}],
['letters', '🔤', 'letters', {he: 'אותיות, תנועות וטונים', en: 'Letters, vowels and tones'}, {
  he: ['• כל אותיות השפה, עם הצליל באותיות עבריות. לחיצה על אות משמיעה אותה.',
    '• בשפות עם כתב מיוחד יש מקטע נוסף: תנועות בתאית ובערבית, צירופים בצרפתית ובאיטלקית, קטקאנה ביפנית, סיומות פינִיִין בסינית, 7 הצורות באמהרית ועוד.',
    '• בשפות טונאליות (תאית, סינית, וייטנאמית) יש כרטיס טונים — שמע איך אותה הברה הופכת למילים שונות.',
    '• כפתור "תרגל" מתרגל רק את האותיות או רק את התנועות.'],
  en: ['• Every letter of the language with its sound in Hebrew letters; tap to hear it.',
    '• Special scripts get an extra section: Thai/Arabic vowels, French/Italian combinations, Japanese katakana, Chinese pinyin finals, Amharic 7 forms and more.',
    '• Tonal languages (Thai, Chinese, Vietnamese) have a tones card.',
    '• "Practise" drills just the letters or just the vowels.']}],
['words', '💬', 'topics', {he: 'מילים ומשפטים', en: 'Words and phrases'}, {
  he: ['• "מילים" ו"משפטים" מסודרים לפי נושאים: אוכל, תחבורה, מלון, קניות, חירום, מספרים, מזג אוויר, רגשות ועוד.',
    '• ליד כל פריט: 🔊 הקראה, 🐢 לאט, ⛶ הצגה בגדול, ו-★ מועדף.',
    '• לכל מילה: הטקסט בשפה, ההגייה באותיות עבריות, התעתיק הלטיני (בשפות עם כתב אחר) והפירוש.',
    '• "המילים שלי" — הוסף מילים משלך (➕). עם חיבור בינה אפשר גם "צור מילים לפי נושא".',
    '• לחיצה ארוכה על מילה או משפט שלך — עריכה.',
    'בהגדרות אפשר לבחור לשון נקבה — והמשפטים יתעדכנו בשפות שבהן זה משנה (ספרדית, רוסית, ערבית, תאית, פורטוגזית, הינדי ועוד).'],
  en: ['• "Words" and "Phrases" are organised by topic: food, transport, hotel, shopping, emergencies, numbers, weather, feelings and more.',
    '• Each item: 🔊 audio, 🐢 slow, ⛶ show big, ★ favourite.',
    '• Each word shows the native text, pronunciation in Hebrew letters, Latin transliteration (for other scripts) and meaning.',
    '• "My words" — add your own (➕); with AI you can also generate words by topic.',
    '• Long-press your own word or phrase to edit it.',
    'In Settings choose female speaker forms — phrases update where it matters.']}],
['practice', '🎯', 'practice', {he: 'תרגול', en: 'Practice'}, {
  he: ['מסך "תרגול" מאפשר לבחור איך לתרגל:',
    '• חזרות שהגיע זמנן — מה שעומד להישכח.',
    '• הטעויות שלי — מילים שטעית בהן.',
    '• המועדפים שלי — רק מה שסימנת ב-★.',
    '• תרגול שמיעה — שומעים ובוחרים.',
    '• תרגול דיבור 🎤 — אומרים בקול והאפליקציה בודקת (צריך מיקרופון).',
    '• בניית משפטים 🧩 — מסדרים מילים מבולגנות למשפט.',
    '• הכתבה ⌨️ — שומעים ומקלידים (בשפות עם כתב אחר מקלידים באותיות לטיניות).',
    '• כרטיסיות 🃏 — הופכים כרטיס ומחליקים: ימינה ידעתי, שמאלה עוד לא.',
    '• או נושא מסוים בלבד.',
    'בסוף כל שיעור — סיכום עם מה שידעת ומה כדאי לחזור עליו.'],
  en: ['The Practice screen lets you choose how to practise:',
    '• Reviews due · My mistakes · My favourites · Listening',
    '• Speaking 🎤 — say it aloud and the app checks (needs a microphone).',
    '• Sentence builder 🧩 — order scrambled words.',
    '• Dictation ⌨️ — listen and type (Latin letters for other scripts).',
    '• Flashcards 🃏 — flip and swipe: right = knew it, left = not yet.',
    '• Or a single topic.',
    'Each lesson ends with a summary.']}],
['dialogs', '🎭', 'dialogs', {he: 'דיאלוגים', en: 'Dialogues'}, {
  he: ['עשר שיחות קצרות מהחיים: במונית, בשוק, במסעדה, במלון, לשאול את הדרך, בביקורת הגבולות, בבית המרקחת, קניית כרטיס סים, בחנות בגדים והזמנת סיור.',
    '• ▶️ השמע — שני קולות, אתה והמקומי.',
    '• "התפקיד שלי" — השורות שלך מוסתרות, ואתה אומר אותן בעצמך (בקול, עם זיהוי דיבור) לפני שחושפים.'],
  en: ['Ten short real-life conversations: taxi, market, restaurant, hotel, directions, passport control, pharmacy, buying a SIM, clothes shop and booking a tour.',
    '• ▶️ Play — two voices, you and the local.',
    '• "My role" hides your lines so you say them yourself before revealing.']}],
['prices', '💰', 'price', {he: 'מחירים ומספרים', en: 'Prices and numbers'}, {
  he: ['• הקלד מספר (עד 999,999) — ותראה ותשמע איך אומרים אותו, עם או בלי המטבע המקומי.',
    '• המנוע יודע את החוקים של כל שפה: 70–90 בצרפתית, ספירה בעשרים בגאורגית, 万 ביפנית, לאח בהינדי ועוד.',
    '• 🎧 "נחש את המחיר" — שומעים מחיר ומקלידים את המספר. מצוין לשווקים!'],
  en: ['• Type any number (up to 999,999) — see and hear it, with or without the local currency.',
    '• The engine knows each language\'s rules (French 70–90, Georgian base-20, Japanese 万, Hindi lakh…).',
    '• 🎧 "Guess the price" — hear a price and type it. Great for markets!']}],
['speak', '🗣️', 'speak', {he: 'דבר בשבילי ✨', en: 'Speak for me ✨'}, {
  he: ['כתוב בעברית מה שאתה רוצה להגיד — והאפליקציה מתרגמת, מקריאה בקול ומציגה בגדול כדי להראות למקומי.',
    '• דורש חיבור בינה. בלי חיבור — יש קישור ל-Google Translate.',
    '• ⭐ שמור — המשפט נכנס ל"המשפטים שלי" ויישאר זמין גם בלי אינטרנט.'],
  en: ['Type in Hebrew what you want to say — the app translates, reads it aloud and shows it big for a local.',
    '• Needs an AI connection; without one there\'s a Google Translate link.',
    '• ⭐ Save — it goes to "My phrases", available offline.']}],
['search', '🔍', 'search', {he: 'איך אומרים?', en: 'How do you say…?'}, {
  he: ['חיפוש מהיר בכל המילים והמשפטים של השפה — בעברית או בשפה עצמה. מהתוצאה אפשר לשמוע, להציג בגדול או לעבור ל"דבר בשבילי".'],
  en: ['Quick search across all words and phrases, in Hebrew or the language itself. From a result: hear it, show it big or send it to "Speak for me".']}],
['chat', '🤖', 'chat', {he: 'שיחה עם בינה ✨', en: 'AI chat ✨'}, {
  he: ['הבינה משחקת את המקומי — נהג, מוכר, מלצר, פקיד קבלה, עובר אורח או חבר בבית קפה — ומדברת רק בשפה שאתה לומד.',
    '• בחר רמה: מתחיל (משפטים קצרים) או מתקדם.',
    '• ענה בכתב, בקול 🎤, או לחץ על אחת מהצעות התשובה.',
    '• טעית או כתבת בעברית? תופיע הצעה "כך אומרים את זה".',
    '• "סיים ותן משוב" — מה היה טוב, מה לשפר, ומשפטים ללמוד שאפשר להוסיף ל"המילים שלי".'],
  en: ['The AI plays a local — driver, vendor, waiter, receptionist, passer-by or café friend — speaking only your target language.',
    '• Choose beginner or intermediate.',
    '• Answer by typing, by voice 🎤, or tap a suggested reply.',
    '• Mistake or Hebrew? You\'ll see "This is how to say it".',
    '• "Finish & get feedback" — what went well, what to improve, and phrases to add to "My words".']}],
['kit', '🧳', 'kit', {he: 'ערכת טיול', en: 'Travel kit'}, {
  he: ['כל מה שצריך בשטח, במקום אחד ועובד בלי אינטרנט:',
    '• מספרי חירום של המדינה — חיוג בלחיצה (לוודא לפני הנסיעה!).',
    '• כרטיסים אישיים: כתובת המלון, אלרגיות, תרופות, איש קשר לחירום. כותבים בעברית ולוחצים "תרגם" (✨), או מקלידים בשפה בעצמך. ⛶ מציג בגדול.',
    '• משפטי חירום מהירים, והמשפטים שסימנת ב-★.'],
  en: ['Everything you need on the ground, offline:',
    '• The country\'s emergency numbers — tap to call (verify before travelling!).',
    '• Personal cards: hotel address, allergies, medication, emergency contact. Write in Hebrew and tap "Translate" (✨), or type it yourself. ⛶ shows it big.',
    '• Quick emergency phrases and your ★ favourites.']}],
['sheet', '📄', 'sheet', {he: 'דף שליפה לטיול', en: 'Trip cheat sheet'}, {
  he: ['דף מרוכז עם המשפטים הכי חשובים — להדפסה, לשמירה כ-PDF בטלפון, או לשליפה מהירה על המסך.',
    '• בוחרים מה ייכנס: הבסיס, מספרים, תחבורה ומלון, אוכל, חירום, המועדפים שלך והמשפטים ששמרת.',
    '• לכל משפט: הפירוש, הטקסט בשפה (גדול) וההגייה. למעלה — מספרי החירום של המדינה.',
    '• "הדפס / שמור PDF" — בחלון ההדפסה בוחרים "שמור כ-PDF", והדף נשמר בטלפון גם בלי אינטרנט ובלי האפליקציה.',
    'נמצא בערכת הטיול.'],
  en: ['A compact page of the most important phrases — to print, save as PDF on your phone, or glance at on screen.',
    '• Choose what goes in: basics, numbers, transport & hotel, food, emergencies, your favourites and saved phrases.',
    '• Each phrase: meaning, the text (large) and pronunciation; the country\'s emergency numbers on top.',
    '• "Print / save PDF" — pick "Save as PDF" in the print dialog to keep it offline, even without the app.',
    'Found in the Travel kit.']}],
['tips', '💡', 'tips', {he: 'טיפים ודקדוק', en: 'Tips and grammar'}, {
  he: ['שישה כרטיסים קצרים לכל שפה על מה שהכי עוזר: נימוס, מבנה המשפט, מלכודות הגייה ותרבות — עם דוגמאות בקול.'],
  en: ['Six short cards per language on what helps most: politeness, sentence structure, pronunciation traps and culture — with audio examples.']}],
['assistant', '🪄', '', {he: 'העוזר החכם ✨', en: 'Smart assistant ✨'}, {
  he: ['כפתור "עוזר" בפינת המסך: מורה אישי שיודע מה אתה לומד כרגע.',
    '• שאל על מילים, דקדוק, הגייה או תרבות.',
    '• בקש "משפטים למסעדה" או "תסביר לי את המילים שקשות לי".',
    '• הוא יכול גם לפתוח לך תרגול, דיאלוגים, מסך או שפה אחרת.',
    'משתמש באותו חיבור בינה שבהגדרות.'],
  en: ['The "Assistant" button in the corner: a personal tutor that knows what you\'re learning.',
    '• Ask about words, grammar, pronunciation or culture.',
    '• Ask for "restaurant phrases" or "explain my difficult words".',
    '• It can open a practice, dialogues, a screen or another language for you.',
    'It uses the same AI connection as Settings.']}],
['progress', '🏅', 'progress', {he: 'התקדמות, יעד שבועי ותגים', en: 'Progress, weekly goal and badges'}, {
  he: ['• מסך "ההתקדמות שלי": הרמות, 7 הימים האחרונים, היעד השבועי והתקדמות בכל השפות.',
    '• 🎯 יעד שבועי — כמה תשובות לתרגל בשבוע (בוחרים בהגדרות).',
    '• 16 תגים על רצפים, כמות תשובות, שליטה בנושא, שיחה ראשונה עם בינה ועוד.'],
  en: ['• "My progress": levels, last 7 days, weekly goal and progress across languages.',
    '• 🎯 Weekly goal — answers per week (set in Settings).',
    '• 16 badges for streaks, answers, mastering a topic, a first AI chat and more.']}],
['voice', '🔊', 'settings', {he: 'קול, הקראה ודיבור', en: 'Voice, read-aloud and speaking'}, {
  he: ['• ההקראה משתמשת בקולות שמותקנים בטלפון או במחשב. בהגדרות אפשר לבחור קול לכל שפה ולשנות מהירות.',
    '• לשפות שאין להן קול במכשיר (יידיש, רוב השפות האפריקאיות, לפעמים גאורגית) — האפליקציה מקריאה את ההגייה בקול העברי, בקירוב.',
    '• לקולות טובים יותר: בטלפון אנדרואיד — הגדרות ← המרת טקסט לדיבור ← התקן נתוני קול. ב-Windows — הדפדפן Edge כולל הרבה קולות איכותיים.',
    '• תרגול דיבור ושיחה בקול צריכים הרשאת מיקרופון ודפדפן שתומך בזיהוי דיבור (Chrome / Edge).'],
  en: ['• Read-aloud uses voices installed on your phone or computer; pick a voice per language and speed in Settings.',
    '• Languages without a device voice (Yiddish, most African languages, sometimes Georgian) are read via the Hebrew voice, approximately.',
    '• Better voices: Android — Settings → Text-to-speech → install voice data. On Windows, Edge has many high-quality voices.',
    '• Speaking practice needs microphone permission and a browser with speech recognition (Chrome / Edge).']}],
['ai', '✨', 'settings:ai', {he: 'חיבור בינה (Pro)', en: 'Connecting AI (Pro)'}, {
  he: ['פיצ׳רי ✨ עובדים עם מפתח משלך (BYOK) לספק בינה:',
    '• Gemini — יש מסלול חינמי. בהגדרות יש קישור ליצירת מפתח ב-Google AI Studio.',
    '• Claude (Anthropic) או ChatGPT (OpenAI) — בתשלום לפי שימוש אצל הספק.',
    '• Ollama — בינה מקומית במחשב, בלי אינטרנט.',
    'המפתח נשמר מוצפן במכשיר בלבד ונשלח רק לספק שבחרת. "בדוק חיבור" מוודא שהכול עובד.',
    'בחשבון Gemini חינמי השרתים לפעמים עמוסים — האפליקציה עוברת אוטומטית למודל אחר ומחכה בסבלנות.'],
  en: ['✨ features use your own key (BYOK):',
    '• Gemini — has a free tier; Settings links to Google AI Studio to create a key.',
    '• Claude (Anthropic) or ChatGPT (OpenAI) — pay-as-you-go with the provider.',
    '• Ollama — local AI on your computer, offline.',
    'The key is stored encrypted on the device and sent only to that provider. "Test connection" checks it.',
    'On free Gemini servers are sometimes busy — the app switches models and waits patiently.']}],
['qa', '🔍', 'qa', {he: 'בדיקת איכות תוכן ✨', en: 'Content quality check ✨'}, {
  he: ['הבינה עוברת על כל המילים והמשפטים של השפה ומסמנת טעויות בתרגום או בהגייה.',
    '• על כל הערה מחליטים: "החל תיקון" (נשמר במכשיר) או "התעלם".',
    '• "העתק דוח" ושלחו אותו ל-AppNest — כך התיקון ייכנס לכולם בגרסה הבאה.',
    '• הבדיקה שומרת התקדמות: אם השרת עמוס, אפשר ללחוץ "המשך" אחר כך.',
    'הבינה לא תמיד צודקת — דובר מקומי הוא הבודק הכי טוב.'],
  en: ['The AI reviews every word and phrase and flags translation or pronunciation mistakes.',
    '• For each note: "Apply fix" (saved on the device) or "Ignore".',
    '• "Copy report" and send it to AppNest so the fix reaches everyone.',
    '• Progress is saved; if servers are busy, tap "Continue" later.',
    'The AI isn\'t always right — a native speaker is the best reviewer.']}],
['settings', '⚙️', 'settings', {he: 'הגדרות', en: 'Settings'}, {
  he: ['• פרופיל: השם שלך, שפת הממשק (עברית, English, Русский, Español, العربية), ולשון זכר/נקבה.',
    '• עיצוב: 5 ערכות צבע (זהב, ספיר, אמרלד, יין, נחושת) ומצב יום/לילה.',
    '• קצב למידה: כמה מילים חדשות ביום, ויעד שבועי.',
    '• הקראה: קול לכל שפה ומהירות.',
    '• חיבור בינה, בדיקת איכות והעוזר.',
    '• גיבוי: ייצוא וייבוא של כל ההתקדמות לקובץ, וייצוא טבלה.',
    '• מדריך הפתיחה, אבחון (לדיווח על תקלה) ומחיקת הכול.'],
  en: ['• Profile: your name, interface language (Hebrew, English, Russian, Spanish, Arabic) and male/female forms.',
    '• Design: 5 colour themes and day/night mode.',
    '• Pace: new words per day and weekly goal.',
    '• Read-aloud: voice per language and speed.',
    '• AI connection, quality check and assistant.',
    '• Backup: export/import all progress to a file, and export a table.',
    '• Welcome guide, diagnostics (for bug reports) and erase all.']}],
['offline', '📲', '', {he: 'התקנה, אופליין ועדכונים', en: 'Install, offline and updates'}, {
  he: ['• התקנה: בטלפון — בתפריט הדפדפן "הוסף למסך הבית". במחשב — אייקון ההתקנה בשורת הכתובת.',
    '• אחרי הפתיחה הראשונה כל השפות נשמרות במכשיר, והאפליקציה עובדת בלי אינטרנט (חוץ מפיצ׳רי ✨).',
    '• עדכונים נכנסים לבד. אם מופיע פס "העדכון לא נטען במלואו — לחץ לרענון", פשוט לחץ עליו.',
    '• ההתקדמות נשמרת בדפדפן — מומלץ לגבות מדי פעם (הגדרות ← גיבוי), במיוחד לפני החלפת טלפון.'],
  en: ['• Install: on a phone use "Add to home screen" in the browser menu; on a computer, the install icon in the address bar.',
    '• After the first open all languages are stored on the device and the app works offline (except ✨ features).',
    '• Updates arrive automatically. If a "tap to refresh" bar appears, just tap it.',
    '• Progress lives in the browser — back up now and then (Settings → Backup), especially before changing phones.']}],
['trouble', '🛠️', '', {he: 'בעיות נפוצות', en: 'Troubleshooting'}, {
  he: ['• אין קול: בדוק שהטלפון לא על שקט, ובחר קול בהגדרות ← הקראה. בשפות בלי קול במכשיר ההקראה בקול העברי.',
    '• המיקרופון לא עובד: אשר הרשאת מיקרופון לאתר, והשתמש ב-Chrome או ב-Edge.',
    '• פיצ׳ר ✨ לא עובד: לחץ "בדוק חיבור" בהגדרות. "השרתים עמוסים" ב-Gemini חינמי — נסה שוב בעוד כמה דקות.',
    '• משהו נראה ישן אחרי עדכון: סגור ופתח את האפליקציה, או לחץ על פס הרענון.',
    '• שגיאה אחרת: הגדרות ← אבחון ← העתק, ושלח ל-appnest55@gmail.com.'],
  en: ['• No sound: check silent mode and pick a voice in Settings → Read-aloud.',
    '• Microphone not working: allow microphone access; use Chrome or Edge.',
    '• ✨ feature failing: "Test connection" in Settings; busy free Gemini servers — try again in a few minutes.',
    '• Looks outdated after an update: close and reopen, or tap the refresh bar.',
    '• Other errors: Settings → Diagnostics → copy, and send to appnest55@gmail.com.']}],
['privacy', '🔒', '', {he: 'פרטיות', en: 'Privacy'}, {
  he: ['אין חשבון ואין שרת של AppNest — הכול נשמר רק במכשיר שלך. טקסט יוצא רק כשאתה משתמש בפיצ׳ר ✨, ורק אל ספק הבינה שחיברת. אין מעקב ואין פרסומות.',
    'המדיניות המלאה: privacy_policy.html (קישור במסך "אודות").'],
  en: ['No account and no AppNest server — everything stays on your device. Text leaves only when you use a ✨ feature, and only to the AI provider you connected. No tracking, no ads.',
    'Full policy: privacy_policy.html (linked on the About screen).']}]
];
window.__MODS.help = '1.19.0';
