/* ===== LingoNest — ui-es.js : interface text (es). Keys missing here fall back to ui-en.js ===== */
LANG.es = {
  "tagline": "Aprende a hablar, en cualquier lugar",
  "helloName": "¡Hola {n}! ¿A dónde vamos hoy?",
  "helloAnon": "¡Hola! ¿A dónde vamos hoy?",
  "chooseLang": "Elegir idioma",
  "wordOfDay": "Palabra del día",
  "streak": "Racha de días",
  "streakN": "Racha: {n} días",
  "level": "Nivel",
  "lvl1": "Letras y sonidos",
  "lvl2": "Palabras de supervivencia",
  "lvl3": "Vocabulario de viaje",
  "lvl4": "Frases de viaje",
  "lvl5": "Palabras cotidianas",
  "continue": "Seguir aprendiendo",
  "ctaSub": "{d} por repasar · {n} nuevas hoy",
  "letters": "Letras",
  "lettersCount": "letras",
  "words": "Palabras",
  "wordsSub": "Por temas",
  "phrases": "Frases",
  "phrasesSub": "Frases listas para viajar",
  "practice": "Práctica",
  "practiceSub": "Repasos, favoritos, errores",
  "speakForMe": "Habla por mí",
  "speakSub": "Escribe una frase y escúchala en {l}",
  "progress": "Mi progreso",
  "progressSub": "Niveles, racha y gráfico semanal",
  "aiStatus": "Conexión IA",
  "connected": "conectada",
  "notConnected": "sin conexión",
  "design": "Diseño",
  "about": "Acerca de",
  "settings": "Ajustes",
  "back": "Volver",
  "home": "Inicio",
  "listen": "Escuchar",
  "slow": "Escuchar despacio",
  "showBig": "Mostrar grande",
  "fav": "Favorito",
  "edit": "Editar",
  "fileWarn": "La app se abrió desde un archivo local. El micrófono, el modo sin conexión y la instalación no funcionarán — ábrela desde su dirección web.",
  "noteEn": "El inglés tiene 26 letras. Cada una tiene nombre y su sonido cambia según la palabra.",
  "noteEs": "El español se lee casi como se escribe. Atención a Ñ, J y la H muda.",
  "noteRu": "El cirílico tiene 33 letras. Algunas parecen latinas pero suenan distinto (Р = r, Н = n, В = v).",
  "noteAr": "El árabe se escribe de derecha a izquierda. Casi todas las letras cambian de forma al inicio, en medio y al final.",
  "noteTh": "El tailandés tiene 44 consonantes y el tono cambia el significado. Las vocales llegan en la próxima versión — las palabras y frases ya las enseñan.",
  "noteGeneric": "Las letras del idioma con su sonido.",
  "practiceLetters": "Practicar letras",
  "seen": "Vista",
  "mastered": "Dominada",
  "cat_greet": "Saludos y cortesía",
  "cat_num": "Números",
  "cat_basic": "Palabras básicas",
  "cat_food": "Comida y restaurante",
  "cat_trans": "Transporte y direcciones",
  "cat_shop": "Compras y dinero",
  "cat_emerg": "Emergencias",
  "cat_time": "Tiempo",
  "cat_phr": "Frases de viaje",
  "cat_mine": "Mis palabras",
  "cat_letters": "Letras",
  "mineEmpty": "Vacío — añade tus palabras",
  "mineEmptyLong": "Aún no hay palabras. Añade una a mano o crea un paquete por tema con IA.",
  "practiceThis": "Practicar este tema",
  "addWord": "Añadir palabra",
  "editWord": "Editar palabra",
  "aiWordsBtn": "Crear palabras por tema",
  "itemsN": "elementos",
  "prDue": "Repasos pendientes",
  "prFav": "Mis favoritos",
  "prWeak": "Mis errores",
  "prListen": "Práctica auditiva",
  "nothingNow": "Ahora no hay nada que practicar aquí. Prueba otro tema o vuelve mañana.",
  "newItem": "Nuevo",
  "sayIt": "Intenta decirlo",
  "gotIt": "Entendido, siguiente",
  "soundsLike": "Suena como:",
  "whichLetter": "¿Qué letra suena así?",
  "qT2M": "¿Qué significa?",
  "qM2T": "¿Cómo se dice?",
  "qA2T": "¿Qué escuchaste?",
  "qT2S": "¿Cómo suena la letra?",
  "qS2T": "¿Qué letra?",
  "right": "¡Correcto!",
  "wrongWas": "La respuesta correcta:",
  "next": "Siguiente",
  "sumLine": "Acertaste {ok} de {t}",
  "sumNew": "Aprendiste {n} elementos nuevos",
  "another": "Otra ronda",
  "listening": "🎤 Escuchando…",
  "saidGood": "¡Genial, te entendí!",
  "saidHeard": "Escuché:",
  "noTTS": "Este navegador no admite lectura en voz alta.",
  "noVoice": "No hay voz de {l} en este dispositivo. En Ajustes se explica cómo añadirla.",
  "noSR": "El reconocimiento de voz funciona en Chrome de escritorio y Android.",
  "srErr": "Falló el reconocimiento de voz",
  "fileMic": "El micrófono solo funciona si la app se abre desde una dirección https.",
  "speakIntro": "Escribe lo que quieres decir. La app lo traduce y lo lee en voz alta, o lo muestra grande para la persona que tienes delante.",
  "modeTranslate": "Traducir",
  "modeDirect": "Escribir en {l}",
  "typeIn": "Escribe en {l}",
  "typeHe": "¿Qué quieres decir?",
  "spkPh": "Por ejemplo: ¿dónde compro una tarjeta SIM?",
  "playIt": "Escuchar",
  "translate": "Traducir y escuchar",
  "noAiHint": "La traducción libre necesita conexión IA (Gemini es gratis). Sin ella, abre Google Translate o escribe directamente en el idioma.",
  "connectAi": "Conectar IA",
  "saveIt": "Guardar",
  "aiDisclaimer": "Traducción con IA: suele ser precisa, pero revisa las frases importantes.",
  "myPhrases": "Mis frases",
  "noPhrases": "Aún no guardaste frases. Las frases guardadas funcionan sin internet.",
  "printBook": "Libro de frases imprimible / PDF",
  "editPhrase": "Editar frase",
  "fSrc": "Frase original",
  "fText": "Texto en {l}",
  "fHeb": "Pronunciación en letras hebreas",
  "fRoman": "Transliteración latina",
  "fMeaning": "Significado",
  "save": "Guardar",
  "delete": "Eliminar",
  "cancel": "Cancelar",
  "close": "Cerrar",
  "saved": "Guardado",
  "deleted": "Eliminado",
  "confirmDelete": "¿Eliminar? No se puede deshacer.",
  "fillBoth": "Completa el significado y el texto.",
  "typeFirst": "Primero escribe una frase.",
  "working": "Trabajando…",
  "needAi": "Esto necesita conexión IA. Puedes conectar Gemini gratis en Ajustes.",
  "aiWordsHint": "Escribe un tema y la IA creará palabras útiles con pronunciación. Se añaden al nivel 5 y a tu práctica.",
  "topic": "Tema",
  "topicPh": "Por ejemplo: playa, hotel, mercado nocturno",
  "howMany": "Cuántas palabras",
  "generate": "Crear palabras",
  "fillTopic": "Escribe un tema.",
  "addedN": "{n} palabras añadidas",
  "aiErr": "Error de IA",
  "aiBadJson": "La IA devolvió una respuesta no válida, inténtalo de nuevo",
  "aiNoKey": "No hay clave de IA",
  "aiOk": "La conexión funciona",
  "last7": "Últimos 7 días",
  "levelsIn": "Niveles en {l}",
  "allLangs": "Todos los idiomas",
  "totalAnswers": "respuestas",
  "levelRule": "Subes de nivel al dominar el 70% del actual. Un elemento se domina tras 3 aciertos seguidos en repasos espaciados.",
  "profile": "Perfil",
  "userName": "Nombre de usuario",
  "uiLang": "Idioma de la interfaz",
  "night": "Noche",
  "day": "Día",
  "th_gold": "Negro y oro",
  "th_sapphire": "Zafiro",
  "th_emerald": "Esmeralda",
  "th_wine": "Burdeos",
  "th_copper": "Cobre",
  "pace": "Ritmo de aprendizaje",
  "paceHint": "Elementos nuevos por día. Los repasos se suman en el momento justo.",
  "paceEasy": "Tranquilo",
  "paceNormal": "Normal",
  "paceFast": "Intensivo",
  "perDay": "día",
  "voiceSec": "Lectura en voz alta",
  "rate": "Velocidad",
  "voiceFor": "Voz para {l}",
  "autoVoice": "Automática (la mejor encontrada)",
  "voiceFound": "Voz encontrada: {v}",
  "voiceMissing": "No hay voz de {l} en este dispositivo, la lectura puede no funcionar.",
  "howAddVoice": "¿Cómo añadir una voz?",
  "addVoiceWin": "Windows: Configuración → Hora e idioma → Voz → Agregar voces, elige el idioma. Luego reinicia el navegador.",
  "addVoiceAnd": "Android: Ajustes → Administración general → Texto a voz → Motor de Google → Instalar datos de voz, elige el idioma.",
  "addVoiceIos": "iPhone: Ajustes → Accesibilidad → Contenido leído → Voces, elige el idioma.",
  "testVoice": "Probar voz",
  "iSpeakAs": "Hablo en género",
  "male": "Masculino",
  "female": "Femenino",
  "genderHint": "Cambia las formas del hablante en frases y traducciones: en tailandés ครับ (khrap) ↔ ค่ะ (kha), y formas masculinas/femeninas en ruso, español y árabe.",
  "aiSec": "Conexión IA (Pro)",
  "aiIntro": "La app funciona completa sin IA. Tu propia clave añade traducción de cualquier frase y palabras por tema.",
  "howKey": "¿Cómo obtengo una clave?",
  "key_gemini": "Gratis, sin tarjeta: entra en AI Studio con tu cuenta de Google, pulsa \"Create API key\", cópiala y pégala aquí.",
  "key_claude": "Entra en Anthropic Console, crea una clave en API Keys, cópiala y pégala aquí. Requiere método de pago.",
  "key_openai": "Entra en OpenAI Platform, crea una clave en API keys, cópiala y pégala aquí. Requiere método de pago.",
  "key_local": "Instala Ollama, ejecuta un modelo (p. ej. llama3.1) y elígelo en la lista. Todo queda en tu ordenador.",
  "apiKey": "Clave API",
  "keySaved": "guardada",
  "saveKey": "Guardar clave",
  "disconnect": "Desconectar",
  "model": "Modelo",
  "autoModel": "Automático (recomendado)",
  "refreshModels": "Actualizar modelos",
  "testAi": "Probar conexión",
  "keyEmpty": "Pega una clave primero.",
  "keyEnc": "La clave se cifra, se guarda en este dispositivo y nunca va en las copias.",
  "keyMem": "El navegador bloquea el almacenamiento cifrado: la clave dura hasta cerrar la app.",
  "confirmDisconnect": "¿Desconectar y borrar la clave del dispositivo?",
  "disconnected": "Desconectado",
  "modelsN": "{n} modelos encontrados",
  "aiPrivacy": "Las acciones de IA envían tu texto solo al proveedor elegido. La clave nunca pasa por servidores de AppNest.",
  "backupSec": "Copia de seguridad",
  "exportJson": "Copia completa (JSON)",
  "importJson": "Restaurar copia",
  "exported": "Archivo descargado",
  "backupNote": "La copia incluye progreso, frases y palabras, sin claves de IA. Restaurar reemplaza todos los datos.",
  "confirmRestore": "¿Restaurar la copia del {d} ({u})? Se reemplazarán todos los datos actuales.",
  "restore": "Restaurar",
  "restored": "Restaurado",
  "badFile": "Este archivo no parece una copia de LingoNest.",
  "persistOk": "El almacenamiento está protegido de la limpieza automática.",
  "persistNo": "El navegador no concedió almacenamiento persistente: haz copias de vez en cuando.",
  "guide": "Guía",
  "showGuide": "Ver guía",
  "diag": "Diagnóstico",
  "noErrors": "No hay errores registrados.",
  "copyDiag": "Copiar informe",
  "copied": "Copiado",
  "copyFail": "No se pudo copiar",
  "resetSec": "Borrar todo",
  "resetHint": "Borra progreso, frases, palabras, ajustes y claves, y vuelve a una instalación nueva.",
  "resetAll": "Borrar todos los datos",
  "reset1": "¿Borrar todos los datos de la app?",
  "reset2": "¿Seguro? Sin copia no hay vuelta atrás.",
  "continueBtn": "Continuar",
  "version": "Versión",
  "developer": "Desarrollo",
  "platform": "Plataforma",
  "storage": "Almacenamiento",
  "onDevice": "Solo en el dispositivo",
  "license": "Licencia",
  "store": "Tienda AppNest",
  "shareApp": "Compartir la app",
  "feedback": "Enviar comentarios",
  "privacy": "Política de privacidad",
  "shareText": "Aprendo idiomas con LingoNest {u}",
  "linkCopied": "Enlace copiado",
  "disclaimer": "El contenido, la pronunciación y las traducciones son ayudas de estudio y pueden ser imprecisos. En una emergencia real contacta a las autoridades.",
  "saveFail": "No se pudo guardar: el almacenamiento puede estar lleno.",
  "backupNudge": "Hace tiempo de tu última copia. Hazla en Ajustes.",
  "phrasebook": "Libro de frases",
  "date": "Fecha",
  "boxInfo": "Dominio {b}/6 · aciertos {c} · errores {w}",
  "notYet": "Aún no practicaste esta letra.",
  "skip": "Saltar",
  "start": "Empecemos",
  "g1t": "Bienvenido a LingoNest",
  "g1b": "Aprende lo básico de un idioma nuevo: letras, palabras y frases para defenderte en un viaje.",
  "g2t": "¿Qué idioma primero?",
  "g2b": "Cambia de idioma cuando quieras desde el inicio. El progreso se guarda por idioma.",
  "g3t": "Niveles a tu ritmo",
  "g3b": "Empieza por las letras y sigue con palabras y frases. \"Seguir aprendiendo\" elige lo nuevo y los repasos.",
  "g4t": "Habla por mí",
  "g4b": "Escribe una frase y la app la lee o la muestra grande. Guarda frases para usarlas sin conexión.",
  "g5t": "Prueba el altavoz",
  "g5b": "La lectura usa las voces del dispositivo. Si un idioma no suena, Ajustes explica cómo añadir una voz.",
  "lvl6": "Conversación",
  "lvl7": "Mundo de palabras",
  "cat_hotel": "Hotel y alojamiento",
  "cat_num2": "Números grandes",
  "cat_days": "Días de la semana",
  "cat_colors": "Colores",
  "cat_people": "Personas y familia",
  "cat_body": "Cuerpo y salud",
  "cat_adj": "Adjetivos",
  "cat_verbs": "Verbos",
  "cat_conv": "Conversación",
  "cat_vowels": "Vocales",
  "searchBtn": "¿Cómo se dice en {l}…?",
  "searchTitle": "Cómo se dice",
  "searchLabel": "Busca una palabra o frase (en cualquier idioma)",
  "searchPh": "Por ejemplo: agua, hotel, cuánto",
  "searchHint": "Empieza a escribir: los resultados salen al instante, incluso sin conexión.",
  "searchNone": "\"{q}\" no está en la lista.",
  "searchTranslate": "Traducir con IA",
  "vowels": "Vocales",
  "practiceVowels": "Practicar vocales",
  "vowelNoteTh": "Las vocales tailandesas se escriben alrededor de la consonante: antes, después, encima o debajo. Aquí aparecen sobre la letra muda อ. Las vocales cortas y largas cambian el significado.",
  "vowelNoteAr": "En árabe las vocales cortas son pequeñas marcas encima y debajo de la letra y casi nunca se escriben. Las largas se escriben con ا و ي.",
  "tones": "Tonos",
  "toneNote": "El tailandés tiene 5 tonos y el tono cambia el significado. Escucha: una sílaba \"mai\", cinco palabras distintas.",
  "tone_mid": "Tono medio",
  "tone_low": "Tono bajo",
  "tone_fall": "Tono descendente",
  "tone_high": "Tono alto",
  "tone_rise": "Tono ascendente",
  "m_mile": "milla",
  "m_new": "nuevo",
  "m_not": "no",
  "m_wood": "madera",
  "m_q": "partícula de pregunta (…?)",
  "twister": "Trabalenguas: \"¿La madera nueva no se quema?\" — todas las palabras suenan \"mai\"",
  "prSay": "Práctica oral",
  "qSAY": "Dilo en voz alta:",
  "skipIt": "Saltar",
  "sayMore": "Aún no, volverá en el repaso",
  "noSpeech": "No oí nada. Pulsa 🎤 y habla cerca del teléfono.",
  "newIn": "Novedades de {v}",
  "wn1": "🪄 Llegó el asistente inteligente: un tutor personal en la esquina que sabe lo que estás aprendiendo.",
  "wn2": "🧩 Construir frases: ordena las palabras. También dentro de las lecciones.",
  "wn3": "⌨️ Dictado: escucha y escribe. 🃏 Tarjetas: repaso rápido deslizando.",
  "wn4": "🔍 Control de calidad: la IA revisa cada palabra y marca errores (en Ajustes).",
  "wn5": "Tu progreso se conservó.",
  "lvl8": "Frases completas",
  "lvl9": "Mis palabras",
  "cat_animals": "Animales",
  "cat_fruits": "Frutas",
  "cat_veggies": "Verduras",
  "cat_dishes": "Comida y mesa",
  "cat_places": "Lugares de la ciudad",
  "cat_things": "Cosas de viaje",
  "cat_s_food": "En el restaurante",
  "cat_s_shop": "De compras",
  "cat_s_move": "Moverse",
  "cat_s_hotel": "En el hotel",
  "cat_s_social": "Conocer gente",
  "cat_s_help": "Ayuda y salud",
  "countWords": "{n} palabras en {c} temas",
  "countPhrases": "{n} frases en {c} situaciones",
  "cat_weather": "El tiempo",
  "cat_jobs": "Profesiones",
  "cat_feel": "Sentimientos",
  "cat_dirs": "Direcciones",
  "dialogs": "Diálogos",
  "dialogsSub": "{n} conversaciones reales",
  "dialogsIntro": "Conversaciones cortas como en un viaje real. Escúchala entera o cambia a \"Mi papel\" y responde tú.",
  "dlg_taxi": "En el taxi",
  "dlg_market": "Regatear en el mercado",
  "dlg_rest": "En el restaurante",
  "dlg_hotel": "Check-in en el hotel",
  "dlg_dir": "Preguntar el camino",
  "dlgLines": "{n} frases",
  "you": "Tú",
  "local": "Local",
  "reveal": "Mostrar",
  "stop": "Parar",
  "playAll": "Escuchar toda la conversación",
  "readMode": "Lectura",
  "roleMode": "Mi papel",
  "roleHint": "Tus frases están ocultas. Lee lo que debes decir, dilo en voz alta y luego muestra la respuesta.",
  "practiceDlg": "Practicar estas frases",
  "prices": "Precios y números",
  "pricesSub": "Escribe un número y escúchalo",
  "pricesIntro": "Escribe cualquier número o precio (hasta 999.999) para ver cómo se escribe y se dice, y escucharlo. Ideal para mercados y taxis.",
  "typeNumber": "Escribe un número",
  "withCur": "Con moneda ({c})",
  "numOnly": "Solo número",
  "check": "Comprobar",
  "arNumNote": "En árabe estándar los números y la moneda cambian de forma según la cantidad. En los dialectos suena algo distinto, pero te entenderán.",
  "guessPrice": "Adivina el precio",
  "guessHint": "Juego de escucha: la app dice un precio en el idioma y tú escribes el número, como en un mercado de verdad.",
  "guessQ": "¿Qué precio oíste?",
  "loadingLang": "Cargando {l}…",
  "loadFail": "No se pudo cargar. Revisa la conexión e inténtalo de nuevo.",
  "updPartial": "Actualización incompleta — toca para recargar",
  "prBuild": "Construir frases",
  "prDict": "Dictado",
  "prCards": "Tarjetas",
  "cardsSub": "Repaso rápido: gira, decide, sigue",
  "cardsDone": "Has repasado {n} tarjetas",
  "cardFlip": "Toca la tarjeta para girarla",
  "knew": "Lo sabía",
  "notYetKnew": "Aún no",
  "swipeHint": "También puedes deslizar: derecha = lo sabía · izquierda = aún no",
  "qBUILD": "Ordena las palabras:",
  "bTap": "Toca las palabras en orden",
  "bClear": "Empezar de nuevo",
  "qDICT": "Escribe lo que oíste",
  "qDICTlat": "Escribe lo que oíste, en letras latinas (como la transliteración)",
  "typeHere": "Escribe aquí",
  "qaTitle": "Control de calidad",
  "qaSub": "La IA revisa todas las palabras y frases del idioma y marca errores de traducción o pronunciación.",
  "qaOpen": "Abrir control de calidad",
  "qaIntro": "El control envía todo el contenido del idioma, por partes, al proveedor de IA que conectaste. Solo marca problemas reales: traducción errónea o poco natural, ortografía o pronunciación engañosa. Tú decides en cada nota. Las correcciones se guardan en el dispositivo y puedes copiar un informe y enviármelo para corregirlo para siempre. Tarda unos minutos; con Gemini gratis puede haber pausas.",
  "qaStart": "Revisar {l}",
  "qaStop": "Parar",
  "qaProgress": "Revisadas {d} de {t}",
  "qaFound": "{n} notas encontradas",
  "qaNone": "No se encontraron problemas 🎉",
  "qaApply": "Aplicar",
  "qaIgnore": "Ignorar",
  "qaApplied": "Corrección aplicada",
  "qaCopy": "Copiar informe",
  "qaCopyHint": "Envíame el informe en el chat y lo corregiré para siempre en el archivo del idioma.",
  "qaFixes": "Correcciones activas en este idioma: {n}",
  "qaReset": "Deshacer todas las correcciones",
  "qaWait": "El proveedor pide ir más despacio — esperando {s} segundos…",
  "qaDone": "Revisión terminada.",
  "asstSec": "Asistente inteligente",
  "asstHint": "El botón 🪄 en la esquina: pregunta lo que quieras del idioma, pide explicaciones, frases de viaje o abre una práctica. Usa la misma conexión de IA.",
  "qaWait2": "Los servidores de IA están ocupados — esperando {s} segundos y seguimos solos (intento {n} de {m})",
  "qaBusyErr": "Los servidores de IA están muy ocupados ahora (frecuente en Gemini gratis). No se perdió nada: el progreso está guardado. Pulsa \"Continuar\" en unos minutos.",
  "qaResume": "Continuar desde {d} de {t}",
  "qaRestart": "Empezar de nuevo"
};
window.__MODS['ui-es'] = '1.5.2';
