/* ===== LingoNest — ui-en.js : interface text (en). Keys missing here fall back to ui-en.js ===== */
LANG.en = {
  "tagline": "Learn to speak, anywhere",
  "helloName": "Hi {n}, where are we going today?",
  "helloAnon": "Hi! Where are we going today?",
  "chooseLang": "Choose language",
  "wordOfDay": "Word of the day",
  "streak": "Day streak",
  "streakN": "Streak: {n} days",
  "level": "Level",
  "lvl1": "Letters & sounds",
  "lvl2": "Survival words",
  "lvl3": "Travel vocabulary",
  "lvl4": "Travel phrases",
  "lvl5": "Everyday words",
  "continue": "Continue learning",
  "ctaSub": "{d} to review · {n} new today",
  "letters": "Letters",
  "lettersCount": "letters",
  "words": "Words",
  "wordsSub": "By topic",
  "phrases": "Phrases",
  "phrasesSub": "Ready-made travel phrases",
  "practice": "Practice",
  "practiceSub": "Reviews, favorites, mistakes",
  "speakForMe": "Speak for me",
  "speakSub": "Type a sentence and hear it in {l}",
  "progress": "My progress",
  "progressSub": "Levels, streak and weekly chart",
  "aiStatus": "AI connection",
  "connected": "connected",
  "notConnected": "not connected",
  "design": "Design",
  "about": "About",
  "settings": "Settings",
  "back": "Back",
  "home": "Home",
  "listen": "Play",
  "slow": "Play slowly",
  "showBig": "Show big",
  "fav": "Favorite",
  "edit": "Edit",
  "fileWarn": "The app was opened from a local file. Microphone, offline mode and install won't work — open it from its web address.",
  "noteEn": "English has 26 letters. Each has a name, and its sound changes from word to word.",
  "noteEs": "Spanish is read almost exactly as written. Watch for Ñ, J (a throaty h) and the silent H.",
  "noteRu": "Cyrillic has 33 letters. Some look like English but sound different (Р = r, Н = n, В = v).",
  "noteAr": "Arabic is written right to left. Most letters change shape at the start, middle and end of a word.",
  "noteTh": "Thai has 44 consonants, and tone changes meaning. Vowels come in the next version — words and phrases already teach them in practice.",
  "noteGeneric": "The letters of the language with their sounds.",
  "practiceLetters": "Practice letters",
  "seen": "Seen",
  "mastered": "Mastered",
  "cat_greet": "Greetings & manners",
  "cat_num": "Numbers",
  "cat_basic": "Basic words",
  "cat_food": "Food & restaurant",
  "cat_trans": "Transport & directions",
  "cat_shop": "Shopping & money",
  "cat_emerg": "Emergency",
  "cat_time": "Time",
  "cat_phr": "Travel phrases",
  "cat_mine": "My words",
  "cat_letters": "Letters",
  "mineEmpty": "Empty — add your own words",
  "mineEmptyLong": "No words here yet. Add one by hand, or create a word pack by topic with AI.",
  "practiceThis": "Practice this topic",
  "addWord": "Add word",
  "editWord": "Edit word",
  "aiWordsBtn": "Create words by topic",
  "itemsN": "items",
  "prDue": "Reviews due now",
  "prFav": "My favorites",
  "prWeak": "My mistakes",
  "prListen": "Listening practice",
  "nothingNow": "Nothing to practice here right now. Try another topic or come back tomorrow.",
  "newItem": "New",
  "sayIt": "Try saying it",
  "gotIt": "Got it, next",
  "soundsLike": "Sounds like:",
  "whichLetter": "Which letter sounds like this?",
  "qT2M": "What does it mean?",
  "qM2T": "How do you say this?",
  "qA2T": "What did you hear?",
  "qT2S": "How does this letter sound?",
  "qS2T": "Which letter?",
  "right": "Correct!",
  "wrongWas": "The right answer:",
  "next": "Next",
  "sumLine": "You got {ok} of {t} right",
  "sumNew": "You learned {n} new items",
  "another": "Another round",
  "listening": "🎤 Listening…",
  "saidGood": "Great, I understood you!",
  "saidHeard": "I heard:",
  "noTTS": "This browser doesn't support read-aloud.",
  "noVoice": "No {l} voice on this device. Settings explain how to add one.",
  "noSR": "Speech recognition works in Chrome on desktop and Android.",
  "srErr": "Speech recognition failed",
  "fileMic": "The microphone only works when the app is opened from an https address.",
  "speakIntro": "Type what you want to say. The app translates it and reads it aloud — or shows it big for the person in front of you.",
  "modeTranslate": "Translate",
  "modeDirect": "Type in {l}",
  "typeIn": "Write in {l}",
  "typeHe": "What do you want to say?",
  "spkPh": "For example: where can I buy a SIM card?",
  "playIt": "Play",
  "translate": "Translate & play",
  "noAiHint": "Free translation needs an AI connection (Gemini is free). Without it, open Google Translate or type directly in the language.",
  "connectAi": "Connect AI",
  "saveIt": "Save",
  "aiDisclaimer": "AI translation — usually accurate, but double-check important sentences.",
  "myPhrases": "My phrases",
  "noPhrases": "No saved phrases yet. Saved phrases work offline too.",
  "printBook": "Printable phrasebook / PDF",
  "editPhrase": "Edit phrase",
  "fSrc": "Original sentence",
  "fText": "Text in {l}",
  "fHeb": "Pronunciation in Hebrew letters",
  "fRoman": "Latin transliteration",
  "fMeaning": "Meaning",
  "save": "Save",
  "delete": "Delete",
  "cancel": "Cancel",
  "close": "Close",
  "saved": "Saved",
  "deleted": "Deleted",
  "confirmDelete": "Delete? This can't be undone.",
  "fillBoth": "Fill in both the meaning and the text.",
  "typeFirst": "Type a sentence first.",
  "working": "Working…",
  "needAi": "This needs an AI connection. You can connect Gemini for free in Settings.",
  "aiWordsHint": "Type a topic and AI will create useful words with pronunciation. They are added to level 5 and to your practice.",
  "topic": "Topic",
  "topicPh": "For example: beach, hotel, night market",
  "howMany": "How many words",
  "generate": "Create words",
  "fillTopic": "Type a topic.",
  "addedN": "{n} words added",
  "aiErr": "AI error",
  "aiBadJson": "The AI returned an invalid answer, try again",
  "aiNoKey": "No AI key set",
  "aiOk": "Connection works",
  "last7": "Last 7 days",
  "levelsIn": "Levels in {l}",
  "allLangs": "All languages",
  "totalAnswers": "answers",
  "levelRule": "You move up a level once you master 70% of the current one. An item counts as mastered after 3 correct answers in a row across spaced reviews.",
  "profile": "Profile",
  "userName": "User name",
  "uiLang": "Interface language",
  "night": "Night",
  "day": "Day",
  "th_gold": "Black & gold",
  "th_sapphire": "Sapphire",
  "th_emerald": "Emerald",
  "th_wine": "Wine",
  "th_copper": "Copper",
  "pace": "Learning pace",
  "paceHint": "New items per day. Reviews come on top of that, at the right time.",
  "paceEasy": "Relaxed",
  "paceNormal": "Normal",
  "paceFast": "Intensive",
  "perDay": "day",
  "voiceSec": "Read-aloud",
  "rate": "Speed",
  "voiceFor": "Voice for {l}",
  "autoVoice": "Automatic (best found)",
  "voiceFound": "Voice found: {v}",
  "voiceMissing": "No {l} voice found on this device, so read-aloud may not work.",
  "howAddVoice": "How do I add a voice?",
  "addVoiceWin": "Windows: Settings → Time & language → Speech → Add voices, and pick the language. Then restart the browser.",
  "addVoiceAnd": "Android: Settings → General management → Text-to-speech → Google engine → Install voice data, and pick the language.",
  "addVoiceIos": "iPhone: Settings → Accessibility → Spoken content → Voices, and pick the language.",
  "testVoice": "Test voice",
  "iSpeakAs": "I speak as",
  "male": "Male",
  "female": "Female",
  "genderHint": "Changes the speaker's forms in phrases and translations: Thai ครับ (khrap) ↔ ค่ะ (kha), plus masculine/feminine forms in Russian, Spanish and Arabic.",
  "aiSec": "AI connection (Pro)",
  "aiIntro": "The app works fully without AI. Adding your own key unlocks translating any sentence and creating words by topic.",
  "howKey": "How do I get a key?",
  "key_gemini": "Free, no credit card: sign in to AI Studio with a Google account, click \"Create API key\", copy and paste it here.",
  "key_claude": "Sign in to the Anthropic Console, create a key under API Keys, copy and paste it here. Requires a payment method.",
  "key_openai": "Sign in to the OpenAI Platform, create a key under API keys, copy and paste it here. Requires a payment method.",
  "key_local": "Install Ollama on your computer, run a model (e.g. llama3.1) and pick it in the list. Everything stays on your computer.",
  "apiKey": "API key",
  "keySaved": "saved",
  "saveKey": "Save key",
  "disconnect": "Disconnect",
  "model": "Model",
  "autoModel": "Automatic (recommended)",
  "refreshModels": "Refresh models",
  "testAi": "Test connection",
  "keyEmpty": "Paste a key first.",
  "keyEnc": "The key is encrypted, stored on this device, and never included in backups.",
  "keyMem": "The browser blocks encrypted storage — the key is kept only until the app closes.",
  "confirmDisconnect": "Disconnect and delete the key from this device?",
  "disconnected": "Disconnected",
  "modelsN": "{n} models found",
  "aiPrivacy": "AI actions send the text you typed only to the provider you chose. The key never passes through any AppNest server.",
  "backupSec": "Backup & sharing",
  "exportJson": "Full backup (JSON)",
  "importJson": "Restore from backup",
  "exported": "File downloaded",
  "backupNote": "The backup includes progress, phrases and words — without AI keys. Restoring replaces all data.",
  "confirmRestore": "Restore the backup from {d} ({u})? All current data will be replaced.",
  "restore": "Restore",
  "restored": "Restored",
  "badFile": "This file doesn't look like a LingoNest backup.",
  "persistOk": "Storage is protected from automatic browser cleanup.",
  "persistNo": "The browser didn't grant persistent storage — back up now and then.",
  "guide": "Guide",
  "showGuide": "Show guide",
  "diag": "Diagnostics",
  "noErrors": "No errors logged.",
  "copyDiag": "Copy report",
  "copied": "Copied",
  "copyFail": "Copy failed",
  "resetSec": "Delete everything",
  "resetHint": "Deletes progress, phrases, words, settings and keys, and returns to a fresh install.",
  "resetAll": "Delete all data",
  "reset1": "Delete all data in the app?",
  "reset2": "Sure? There is no way back without a backup.",
  "continueBtn": "Continue",
  "version": "Version",
  "developer": "Developer",
  "platform": "Platform",
  "storage": "Storage",
  "onDevice": "On this device only",
  "license": "License",
  "store": "AppNest store",
  "shareApp": "Share the app",
  "feedback": "Send feedback",
  "privacy": "Privacy policy",
  "shareText": "Learning languages with LingoNest {u}",
  "linkCopied": "Link copied",
  "disclaimer": "Content, pronunciation guides and translations are learning aids and may be inaccurate. In a real emergency contact the proper authorities.",
  "saveFail": "Saving failed — storage may be full.",
  "backupNudge": "It's been a while since your last backup. Back up in Settings.",
  "phrasebook": "Phrasebook",
  "date": "Date",
  "boxInfo": "Mastery {b}/6 · right {c} · wrong {w}",
  "notYet": "You haven't practiced this letter yet.",
  "skip": "Skip",
  "start": "Let's start",
  "g1t": "Welcome to LingoNest",
  "g1b": "Learn the basics of a new language: letters, words and phrases to get by on a trip, with pronunciation you can read.",
  "g2t": "Which language first?",
  "g2b": "Switch languages anytime from the home screen. Progress is saved per language.",
  "g3t": "Levels at your pace",
  "g3b": "Start with letters, move on to words and phrases. \"Continue learning\" picks what's new and what needs review.",
  "g4t": "Speak for me",
  "g4b": "Type a sentence and the app reads it aloud or shows it big to the person in front of you. Save phrases for offline use.",
  "g5t": "Check your speaker",
  "g5b": "Read-aloud uses your device's voices. If a language is silent, Settings explain how to add a voice.",
  "lvl6": "Conversation",
  "lvl7": "World of words",
  "cat_hotel": "Hotel & stay",
  "cat_num2": "Big numbers",
  "cat_days": "Days of the week",
  "cat_colors": "Colors",
  "cat_people": "People & family",
  "cat_body": "Body & health",
  "cat_adj": "Adjectives",
  "cat_verbs": "Verbs",
  "cat_conv": "Conversation",
  "cat_vowels": "Vowels",
  "searchBtn": "How do you say it in {l}…?",
  "searchTitle": "How do you say",
  "searchLabel": "Search a word or phrase (in any language)",
  "searchPh": "For example: water, hotel, how much",
  "searchHint": "Start typing — results appear instantly, even offline.",
  "searchNone": "\"{q}\" isn't in the word list.",
  "searchTranslate": "Translate with AI",
  "vowels": "Vowels",
  "practiceVowels": "Practice vowels",
  "vowelNoteTh": "Thai vowels are written around the consonant — before, after, above or below it. Here they sit on the silent letter อ. Short and long vowels change the meaning.",
  "vowelNoteAr": "In Arabic, short vowels are small marks above and below the letter and are usually left out of normal text. Long vowels are written with ا و ي.",
  "tones": "Tones",
  "toneNote": "Thai has 5 tones, and tone changes meaning. Hear the difference: one syllable \"mai\", five different words.",
  "tone_mid": "Mid tone",
  "tone_low": "Low tone",
  "tone_fall": "Falling tone",
  "tone_high": "High tone",
  "tone_rise": "Rising tone",
  "m_mile": "mile",
  "m_new": "new",
  "m_not": "not",
  "m_wood": "wood",
  "m_q": "question word (…?)",
  "twister": "Tongue twister: \"Doesn't new wood burn?\" — every word sounds like \"mai\"",
  "prSay": "Speaking practice",
  "qSAY": "Say it out loud:",
  "skipIt": "Skip",
  "sayMore": "Not yet — it will come back in review",
  "noSpeech": "I didn't hear anything. Tap 🎤 and speak close to the phone.",
  "newIn": "What's new in {v}",
  "wn1": "🇫🇷 French: 407 words and phrases, alphabet and sound combinations (ou, an, on…), dialogues, numbers (including the French 70/80/90), tips and emergency numbers.",
  "wn2": "🇲🇦 Moroccan Arabic (Darija): the Arabic actually spoken on Moroccan streets — 407 words and phrases, prices in dirham, tips (including the \"ryal\" trap) and emergency numbers.",
  "wn3": "For Darija, read-aloud uses a general Arabic voice unless your device has a Moroccan one (Edge on Windows does).",
  "wn4": "AI chat, travel kit and quality check work in both new languages.",
  "wn5": "Your progress was kept as it is.",
  "lvl8": "Full sentences",
  "lvl9": "My words",
  "cat_animals": "Animals",
  "cat_fruits": "Fruits",
  "cat_veggies": "Vegetables",
  "cat_dishes": "Food & table",
  "cat_places": "Places in town",
  "cat_things": "Travel items",
  "cat_s_food": "At the restaurant",
  "cat_s_shop": "Shopping",
  "cat_s_move": "Getting around",
  "cat_s_hotel": "At the hotel",
  "cat_s_social": "Meeting people",
  "cat_s_help": "Help & health",
  "countWords": "{n} words in {c} topics",
  "countPhrases": "{n} phrases in {c} situations",
  "cat_weather": "Weather",
  "cat_jobs": "Jobs",
  "cat_feel": "Feelings",
  "cat_dirs": "Directions",
  "dialogs": "Dialogues",
  "dialogsSub": "{n} real-life conversations",
  "dialogsIntro": "Short conversations like on a real trip. Play the whole thing, or switch to \"My role\" and answer yourself.",
  "dlg_taxi": "In a taxi",
  "dlg_market": "Bargaining at the market",
  "dlg_rest": "At a restaurant",
  "dlg_hotel": "Hotel check-in",
  "dlg_dir": "Asking the way",
  "dlgLines": "{n} lines",
  "you": "You",
  "local": "Local",
  "reveal": "Show",
  "stop": "Stop",
  "playAll": "Play the whole conversation",
  "readMode": "Read",
  "roleMode": "My role",
  "roleHint": "Your lines are hidden. Read what you need to say, try it out loud, then reveal the answer.",
  "practiceDlg": "Practice these lines",
  "prices": "Prices & numbers",
  "pricesSub": "Type a number and hear it",
  "pricesIntro": "Type any number or price (up to 999,999) to see how it's written and said, and hear it aloud. Perfect for markets and taxis.",
  "typeNumber": "Type a number",
  "withCur": "With currency ({c})",
  "numOnly": "Number only",
  "check": "Check",
  "arNumNote": "In standard Arabic, numbers and the currency change form with the amount. Spoken dialects sound a bit different, but you'll be understood.",
  "guessPrice": "Guess the price",
  "guessHint": "Listening game: the app says a price in the language and you type the number, like at a real market.",
  "guessQ": "Which price did you hear?",
  "loadingLang": "Loading {l}…",
  "loadFail": "Loading failed. Check your connection and try again.",
  "updPartial": "Update incomplete — tap to refresh",
  "prBuild": "Sentence builder",
  "prDict": "Dictation",
  "prCards": "Flashcards",
  "cardsSub": "Quick review — flip, decide, next",
  "cardsDone": "You went through {n} cards",
  "cardFlip": "Tap the card to flip it",
  "knew": "I knew it",
  "notYetKnew": "Not yet",
  "swipeHint": "You can also swipe: right = knew it · left = not yet",
  "qBUILD": "Put the words in order:",
  "bTap": "Tap the words in the right order",
  "bClear": "Start over",
  "qDICT": "Type what you heard",
  "qDICTlat": "Type what you heard — in Latin letters (like the transliteration)",
  "typeHere": "Type here",
  "qaTitle": "Content quality check",
  "qaSub": "The AI goes through every word and phrase of the language and flags translation or pronunciation mistakes.",
  "qaOpen": "Open quality check",
  "qaIntro": "The check sends all of the language's content, in batches, to the AI provider you connected. It flags only real problems: wrong or unnatural translations, spelling mistakes, or pronunciation that would mislead. You decide on each note. Fixes are stored on the device, and you can copy a report and send it to me to fix permanently in the language file. It takes a few minutes; on a free Gemini account there may be short waits between batches.",
  "qaStart": "Check {l}",
  "qaStop": "Stop",
  "qaProgress": "Checked {d} of {t}",
  "qaFound": "{n} notes found",
  "qaNone": "No problems found 🎉",
  "qaApply": "Apply fix",
  "qaIgnore": "Ignore",
  "qaApplied": "Fix applied",
  "qaCopy": "Copy report",
  "qaCopyHint": "Send me the report in chat and I'll build the fixes permanently into the language file.",
  "qaFixes": "Active fixes in this language: {n}",
  "qaReset": "Undo all fixes",
  "qaWait": "The provider asked to slow down — waiting {s} seconds…",
  "qaDone": "Check finished.",
  "asstSec": "Smart assistant",
  "asstHint": "The 🪄 assistant button in the corner: ask anything about the language, get explanations, travel phrases, or open a practice. It uses the same AI connection you set above.",
  "qaWait2": "The AI servers are busy — waiting {s} seconds, then continuing automatically (try {n} of {m})",
  "qaBusyErr": "The AI servers are very busy right now (common on the free Gemini tier). Nothing was lost — progress is saved. Tap \"Continue\" in a few minutes.",
  "qaResume": "Continue from {d} of {t}",
  "qaRestart": "Start over",
  "weekGoal": "Weekly goal",
  "weekN": "{n}/{g} this week",
  "weekDone": "Weekly goal reached — well done!",
  "weekLeft": "{n} more answers to reach this week's goal",
  "weekGoalHint": "Weekly goal: how many answers to practice per week (weeks start on Sunday).",
  "perWeek": "per week",
  "badges": "Badges",
  "badgeNew": "New badge: {b}",
  "chat": "Chat with AI",
  "chatSub": "Practice a real conversation",
  "chatIntro": "The AI plays the local — driver, vendor, waiter — and speaks only the language you're learning. Answer by typing or speaking; if you make a mistake or write in Hebrew it shows how to say it. At the end you get feedback and phrases to learn.",
  "lvEasy": "Beginner",
  "lvMid": "Intermediate",
  "scen_taxi": "In a taxi",
  "scen_market": "Bargaining at the market",
  "scen_rest": "At a restaurant",
  "scen_hotel": "Hotel check-in",
  "scen_dir": "Asking the way",
  "scen_social": "Small talk at a café",
  "scen_free": "Free conversation",
  "chatTr": "Translation",
  "chatEnd": "Finish & get feedback",
  "chatNew": "New conversation",
  "chatPh": "Write in {l} — or in Hebrew if you don't know how",
  "chatSend": "Send",
  "chatBetter": "This is how to say it:",
  "chatSumTitle": "Conversation feedback",
  "chatGood": "What went well",
  "chatImprove": "What to improve",
  "chatPhrases": "Phrases worth learning",
  "chatAddMine": "Add to \"My words\"",
  "chatSugg": "You could answer, for example:",
  "kit": "Travel kit",
  "kitSub": "Emergency, address, allergies",
  "kitIntro": "Everything you need on the ground, in one place and offline: emergency numbers, personal cards to show locals, and one-tap emergency phrases.",
  "kitEmerg": "Emergency numbers",
  "kitEmergNote": "For reference only — check them before your trip. On mobile, 112 works almost everywhere. Tap a number to call.",
  "kitCards": "My cards",
  "kitEmpty": "No cards yet. Add your hotel address, allergies or medication — then show them big to anyone who needs to see.",
  "kt_hotel": "Hotel address",
  "kt_allergy": "Allergies",
  "kt_meds": "Medication & health",
  "kt_contact": "Emergency contact",
  "kt_custom": "Other card",
  "kitHint_hotel": "Copy the hotel name and address in the local language from your booking site and paste it below — so you can show the driver exactly where.",
  "kitHint_allergy": "Write in Hebrew what you're allergic to and how serious it is; the AI will translate. You can also type directly in the language.",
  "kitHint_meds": "Write in Hebrew which medication you take or a condition a doctor or pharmacist should know about.",
  "kitHint_contact": "Name and phone of someone to call in an emergency.",
  "kitHint_custom": "Anything you want to show a local: a booking, a special request, a route.",
  "kitTitle": "Title",
  "kitSrc": "In Hebrew (to translate)",
  "kitTranslate": "Translate to {l}",
  "kitText": "Text in {l} (what is shown)",
  "kitQuick": "Quick emergency phrases",
  "kitFavs": "My favorite phrases",
  "kitFavsEmpty": "Tap ★ next to a word or phrase to have it here for quick access.",
  "tips": "Tips & grammar",
  "tipsSub": "How the language works",
  "tipsIntro": "Short cards on what helps most to understand the language and the people — no long grammar lessons.",
  "tipsAsk": "Want more? Ask the 🪄 assistant in the corner.",
  "searchSub": "Quick search in all words",
  "b_first": "First step",
  "bd_first": "Your first answer",
  "b_ans100": "Hundred",
  "bd_ans100": "100 answers",
  "b_ans500": "Five hundred",
  "bd_ans500": "500 answers",
  "b_ans1000": "Thousand",
  "bd_ans1000": "1000 answers",
  "b_streak3": "3 days",
  "bd_streak3": "3-day streak",
  "b_streak7": "One week",
  "bd_streak7": "7-day streak",
  "b_streak30": "One month",
  "bd_streak30": "30-day streak",
  "b_week": "Weekly goal",
  "bd_week": "Reached the weekly goal",
  "b_letters": "Letter champ",
  "bd_letters": "Mastered every letter of a language",
  "b_topic": "Whole topic",
  "bd_topic": "Mastered a full topic",
  "b_level": "Level 3",
  "bd_level": "Reached level 3 in a language",
  "b_poly": "Polyglot",
  "bd_poly": "Learning 3 languages",
  "b_chat": "First chat",
  "bd_chat": "A conversation with AI",
  "b_role": "Actor",
  "bd_role": "Practiced \"My role\"",
  "b_speaker": "Speaker",
  "bd_speaker": "10 correct spoken answers",
  "b_kit": "Ready to go",
  "bd_kit": "Created a travel-kit card"
};
window.__MODS['ui-en'] = '1.7.0';
